import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code'

export default {
  name: 'Distorted Ripple',
  description: 'A grid-based ripple effect that accelerates and distorts as it expands. It transitions from a smooth, perfect circle at the center to a chaotic, jagged ring at the edges, featuring customizable speed ramps and noise levels.',
  author: {
    name: "Aryan",
    imageUrl: 'https://pbs.twimg.com/profile_images/1927618320246919168/nvaCh-o8_400x400.jpg',
    redirectUrl: 'https://tarnished.lol'
  },
  tags: ['animated', 'shader', 'webgl', 'dots', 'ripple', 'distortion', 'fire'],
  defaultProps: {
    cycleDuration: 4.0,
    delayTime: 0.0,
    gridSize: 150.0,
    gapPixels: 2.0,
    noiseScale: 3.0,
    speedRamp: 1.3,
    distortionStart: 0.2,
    distortionEnd: 0.3,
    burnWidth: 0.05,
    coreColor: '#349EE9',
    glowColor: '#01588E',
    backgroundColor: '#000000',
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'coreColor',
      label: 'Core Color',
      type: 'color',
      defaultValue: '#48B8FF',
      description: 'The primary color of the ripple ring.',
    },
    {
      key: 'glowColor',
      label: 'Glow Color',
      type: 'color',
      defaultValue: '#48B8FF',
      description: 'The secondary glow color mixed in at the edges.',
    },
    {
      key: 'backgroundColor',
      label: 'Background Color',
      type: 'color',
      defaultValue: '#000000',
      description: 'The background color of the canvas.',
    },

    {
      key: 'cycleDuration',
      label: 'Cycle Duration',
      type: 'slider',
      min: 1,
      max: 20,
      step: 0.5,
      defaultValue: 10.0,
      description: 'Total time for one ripple to fully expand and fade.',
    },
    {
      key: 'delayTime',
      label: 'Delay Time',
      type: 'slider',
      min: 0,
      max: 5,
      step: 0.5,
      defaultValue: 2.0,
      description: 'Pause time before the next ripple starts.',
    },
    {
      key: 'speedRamp',
      label: 'Speed Ramp',
      type: 'slider',
      min: 0.5,
      max: 5.0,
      step: 0.1,
      defaultValue: 2.5,
      description: 'Acceleration curve. 1.0 is linear. Higher values start slow and zoom out fast.',
    },

    {
      key: 'distortionStart',
      label: 'Start Distortion',
      type: 'slider',
      min: 0,
      max: 1.0,
      step: 0.05,
      defaultValue: 0.0,
      description: 'How distorted the circle is when it spawns at the center (0.0 = perfect circle).',
    },
    {
      key: 'distortionEnd',
      label: 'End Distortion',
      type: 'slider',
      min: 0,
      max: 1.0,
      step: 0.05,
      defaultValue: 0.3,
      description: 'How distorted the circle is when it reaches the edge.',
    },
    {
      key: 'noiseScale',
      label: 'Noise Scale',
      type: 'slider',
      min: 1.0,
      max: 10.0,
      step: 0.5,
      defaultValue: 3.0,
      description: 'The scale/frequency of the noise pattern used for distortion.',
    },

    {
      key: 'gridSize',
      label: 'Grid Density',
      type: 'slider',
      min: 20,
      max: 300,
      step: 5,
      defaultValue: 60.0,
      description: 'Number of grid cells across the screen.',
    },
    {
      key: 'gapPixels',
      label: 'Gap Pixels',
      type: 'slider',
      min: 0,
      max: 5,
      step: 0.5,
      defaultValue: 2.0,
      description: 'Space between dots in pixels.',
    },
    {
      key: 'burnWidth',
      label: 'Ring Width',
      type: 'slider',
      min: 0.01,
      max: 0.2,
      step: 0.01,
      defaultValue: 0.05,
      description: 'Thickness of the main ripple ring.',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
