import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code'
export default {
  name: 'CRT Effect',
  description: 'A CRT monitor effect with barrel distortion curvature, scanlines, and retro display artifacts for images and videos.',
  author: {
    name: "Ninjafire",
    imageUrl: 'https://pbs.twimg.com/profile_images/2006007847742758912/nWXptCKJ_400x400.jpg',
    redirectUrl: 'https://ninjafire.xyz'
  },
  tags: ['crt', 'retro', 'monitor', 'curvature', 'scanlines', 'vintage'],
  defaultProps: {
    mediaType: 'image',
    source: '/data/akaza.jpg',
    objectFit: 'cover',
    brightness: 0,
    contrast: 0,
    curvature: false,
    curvatureIntensity: 0.4,
    scanlines: 1.3,
    vignette: 0.5,
    rgbShift: 0.6,
    flicker: 1,
    noise: 0.7,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'mediaType',
      label: 'Media Type',
      type: 'select',
      options: ['image', 'video'],
      defaultValue: 'image',
      description: 'Choose between processing a static image or a looping video.',
    },
    {
      key: 'source',
      label: 'Media Source',
      type: 'media-input',
      defaultValue: '/data/akaza.jpg',
      defaultImage: '/data/akaza.jpg',
      defaultVideo: '/data/akaza.mp4',
      description: 'Upload an image or video file to apply the CRT effect.',
      mediaTypeKey: 'mediaType',
    },
    {
      key: 'objectFit',
      label: 'Object Fit',
      type: 'select',
      options: ['contain', 'cover', 'fill'],
      defaultValue: 'cover',
      description: 'Control how the media fits within the canvas.',
    },
    {
      key: 'curvature',
      label: 'Curvature',
      type: 'toggle',
      defaultValue: true,
      description: 'Enable barrel distortion to simulate a curved CRT screen.',
    },
    {
      key: 'curvatureIntensity',
      label: 'Curvature Intensity',
      type: 'slider',
      min: 0,
      max: 1.5,
      step: 0.01,
      defaultValue: 0.4,
      description: 'Strength of the barrel distortion curvature effect.',
    },
    {
      key: 'scanlines',
      label: 'Scanlines',
      type: 'slider',
      min: 0,
      max: 3,
      step: 0.01,
      defaultValue: 1.3,
      description: 'Intensity of horizontal CRT scanline darkening.',
    },
    {
      key: 'vignette',
      label: 'Vignette',
      type: 'slider',
      min: 0,
      max: 1.5,
      step: 0.01,
      defaultValue: 0.5,
      description: 'Edge darkening around the screen border.',
    },
    {
      key: 'rgbShift',
      label: 'RGB Shift',
      type: 'slider',
      min: 0,
      max: 2,
      step: 0.01,
      defaultValue: 0.6,
      description: 'Chromatic aberration / color channel separation.',
    },
    {
      key: 'flicker',
      label: 'Flicker',
      type: 'slider',
      min: 0,
      max: 4,
      step: 0.01,
      defaultValue: 1,
      description: 'Subtle overall brightness oscillation.',
    },
    {
      key: 'noise',
      label: 'Noise',
      type: 'slider',
      min: 0,
      max: 1.5,
      step: 0.01,
      defaultValue: 0.7,
      description: 'Static grain noise overlay.',
    },
    {
      key: 'brightness',
      label: 'Brightness',
      type: 'slider',
      min: -100,
      max: 100,
      step: 1,
      defaultValue: 0,
      description: 'Adjust the overall image brightness.',
    },
    {
      key: 'contrast',
      label: 'Contrast',
      type: 'slider',
      min: -100,
      max: 100,
      step: 1,
      defaultValue: 0,
      description: 'Adjust the overall image contrast.',
    }
  ],
} as Omit<BackgroundConfig, 'id'>;
