import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code';

export default {
  name: 'Animals',
  description: 'A pixel-art sprite animal that follows your mouse cursor with walk and idle animations. Choose from bull, sheep, pig, chick, or turkey.',
  author: {
    name: "Aryan",
    imageUrl: 'https://pbs.twimg.com/profile_images/1927618320246919168/nvaCh-o8_400x400.jpg',
    redirectUrl: 'https://tarnished.lol'
  },
  tags: ['sprite', 'pixel-art', 'interactive', 'mouse-follow', 'canvas', 'animation'],
  defaultProps: {
    animal: 'sheep',
    speed: 4,
    scale: 3,
    initialX: 50,
    initialY: 50,
    transparent: true,
    backgroundColor: '#4a7c59',
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'animal',
      label: 'Animal',
      type: 'select',
      options: ['bull', 'sheep', 'pig', 'chick', 'turkey'],
      defaultValue: 'sheep',
      description: 'The animal sprite to display.',
    },
    {
      key: 'speed',
      label: 'Speed',
      type: 'slider',
      min: 1,
      max: 10,
      step: 0.5,
      defaultValue: 4,
      description: 'How fast the animal moves toward the cursor.',
    },
    {
      key: 'scale',
      label: 'Scale',
      type: 'slider',
      min: 1,
      max: 8,
      step: 0.5,
      defaultValue: 3,
      description: 'Size multiplier for the animal sprite.',
    },
    {
      key: 'initialX',
      label: 'Start X',
      type: 'slider',
      min: 0,
      max: 100,
      step: 5,
      defaultValue: 50,
      description: 'Initial horizontal position as a percentage of screen width.',
    },
    {
      key: 'initialY',
      label: 'Start Y',
      type: 'slider',
      min: 0,
      max: 100,
      step: 5,
      defaultValue: 50,
      description: 'Initial vertical position as a percentage of screen height.',
    },
    {
      key: 'transparent',
      label: 'Transparent',
      type: 'toggle',
      defaultValue: true,
      description: 'When enabled, the background is transparent (overlay mode).',
    },
    {
      key: 'backgroundColor',
      label: 'Background Color',
      type: 'color',
      defaultValue: '#4a7c59',
      description: 'Background fill color (only visible when transparent is off).',
    },
    {
      key: 'downloadSprite',
      label: 'Sprite Sheet',
      type: 'download',
      defaultValue: '/data/Sheep_animation_with_shadow.png',
      downloadUrlKey: 'animal',
      downloadUrls: {
        bull: '/data/Bull_animation_with_shadow.png',
        sheep: '/data/Sheep_animation_with_shadow.png',
        pig: '/data/Piglet_animation_with_shadow.png',
        chick: '/data/Chick_animation_with_shadow.png',
        turkey: '/data/Turkey_animation_with_shadow.png',
      },
      description: 'Download the sprite sheet for the currently selected animal.',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
