import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code'

export default {
  name: 'Eye Floaters',
  description: 'A WebGL shader that renders transparent, organic floater shapes drifting across a soft gradient sky with optional cloud layers — inspired by the vitreous floaters you see in your own eyes.',
  author: {
    name: "Aryn",
    imageUrl: 'https://pbs.twimg.com/profile_images/1927618320246919168/nvaCh-o8_400x400.jpg',
    redirectUrl: 'https://tarnished.lol'
  },
  tags: ['webgl', 'shader', 'organic', 'floaters', 'glass', 'clouds', 'gradient'],
  defaultProps: {
    topColor: '#8caae6',
    bottomColor: '#a4c4ed',
    speed: 0.4,
    scale: 2,
    density: 1,
    thickness: 0.5,
    showClouds: true,
    cloudColor: '#ffffff',
    cloudOpacity: 2,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'topColor',
      label: 'Top Color',
      type: 'color',
      defaultValue: '#8caae6',
      description: 'The gradient color at the top of the canvas.',
    },
    {
      key: 'bottomColor',
      label: 'Bottom Color',
      type: 'color',
      defaultValue: '#a4c4ed',
      description: 'The gradient color at the bottom of the canvas.',
    },
    {
      key: 'speed',
      label: 'Speed',
      type: 'slider',
      min: 0.1,
      max: 2,
      step: 0.1,
      defaultValue: 0.4,
      description: 'How fast the floaters drift and wiggle.',
    },
    {
      key: 'scale',
      label: 'Scale',
      type: 'slider',
      min: 1,
      max: 6,
      step: 0.5,
      defaultValue: 2,
      description: 'Controls the zoom level of the floater grid. Higher values = more floaters.',
    },
    {
      key: 'density',
      label: 'Density',
      type: 'slider',
      min: 0.1,
      max: 1,
      step: 0.1,
      defaultValue: 1,
      description: 'The probability of a floater appearing in each grid cell.',
    },
    {
      key: 'thickness',
      label: 'Thickness',
      type: 'slider',
      min: 0.1,
      max: 2,
      step: 0.1,
      defaultValue: 0.5,
      description: 'Controls the thickness of the floater bodies.',
    },
    {
      key: 'showClouds',
      label: 'Show Clouds',
      type: 'toggle',
      defaultValue: true,
      description: 'Toggle the cloud layer on or off.',
    },
    {
      key: 'cloudColor',
      label: 'Cloud Color',
      type: 'color',
      defaultValue: '#ffffff',
      description: 'The color of the cloud layer.',
    },
    {
      key: 'cloudOpacity',
      label: 'Cloud Opacity',
      type: 'slider',
      min: 0,
      max: 4,
      step: 0.1,
      defaultValue: 2,
      description: 'The opacity/intensity of the cloud layer.',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
