import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code'

export default {
  name: 'Dotted Surface',
  description: 'A 3D grid of dots that ripple with sine wave motion in perspective',
  author: {
    name: "Ninjafire",
    imageUrl: 'https://pbs.twimg.com/profile_images/2006007847742758912/nWXptCKJ_400x400.jpg',
    redirectUrl: 'https://ninjafire.xyz'
  },
  tags: ['animated', 'shader', '3d', 'dots', 'wave', 'grid'],
  defaultProps: {
    dotColor: '#d9d9d9',
    shape: 'circle',
    speed: 0.1,
    waveAmplitude: 50.0,
    waveFreqX: 0.3,
    waveFreqY: 0.5,
    pointSize: 5.0,
    separation: 150,
    gridX: 40,
    gridY: 200,
    opacity: 0.8,
    cameraHeight: -555,
    cameraDistance: -1220,
    fov: 60,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'shape',
      label: 'Shape',
      type: 'select',
      options: ['circle', 'square', 'triangle', 'diamond'],
      defaultValue: 'circle',
      description: 'Shape of each dot in the grid',
    },
    {
      key: 'dotColor',
      label: 'Dot Color',
      type: 'color',
      defaultValue: '#d9d9d9',
      description: 'Color of the dots',
    },
    {
      key: 'speed',
      label: 'Speed',
      type: 'slider',
      min: 0.01,
      max: 0.5,
      step: 0.01,
      defaultValue: 0.1,
      description: 'Animation speed of the wave motion',
    },
    {
      key: 'waveAmplitude',
      label: 'Wave Height',
      type: 'slider',
      min: 5,
      max: 250,
      step: 5,
      defaultValue: 50.0,
      description: 'Height of the wave displacement',
    },
    {
      key: 'waveFreqX',
      label: 'Wave Freq X',
      type: 'slider',
      min: 0.05,
      max: 5.0,
      step: 0.05,
      defaultValue: 0.3,
      description: 'Wave frequency along the X axis',
    },
    {
      key: 'waveFreqY',
      label: 'Wave Freq Y',
      type: 'slider',
      min: 0.05,
      max: 5.0,
      step: 0.05,
      defaultValue: 0.5,
      description: 'Wave frequency along the Y axis',
    },
    {
      key: 'pointSize',
      label: 'Dot Size',
      type: 'slider',
      min: 1,
      max: 30,
      step: 0.5,
      defaultValue: 5.0,
      description: 'Base size of each dot',
    },
    {
      key: 'separation',
      label: 'Grid Spacing',
      type: 'slider',
      min: 50,
      max: 400,
      step: 10,
      defaultValue: 150,
      description: 'Distance between dots in the grid',
    },
    {
      key: 'gridX',
      label: 'Dots X',
      type: 'slider',
      min: 10,
      max: 500,
      step: 5,
      defaultValue: 40,
      description: 'Number of dots along the X axis',
    },
    {
      key: 'gridY',
      label: 'Dots Y',
      type: 'slider',
      min: 10,
      max: 500,
      step: 5,
      defaultValue: 200,
      description: 'Number of dots along the Y axis',
    },
    {
      key: 'opacity',
      label: 'Opacity',
      type: 'slider',
      min: 0.1,
      max: 1.0,
      step: 0.05,
      defaultValue: 0.8,
      description: 'Transparency of the dots',
    },
    {
      key: 'cameraHeight',
      label: 'Camera Height',
      type: 'slider',
      min: -800,
      max: 0,
      step: 10,
      defaultValue: -555,
      description: 'Vertical position of the camera',
    },
    {
      key: 'cameraDistance',
      label: 'Camera Distance',
      type: 'slider',
      min: -3000,
      max: -400,
      step: 20,
      defaultValue: -1220,
      description: 'How far the camera is from the grid',
    },
    {
      key: 'fov',
      label: 'Field of View',
      type: 'slider',
      min: 20,
      max: 120,
      step: 5,
      defaultValue: 60,
      description: 'Camera field of view angle in degrees',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
