import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code'

export default {
  name: 'Kinetic Distortion',
  description: 'An interactive text background where horizontal slices distort and stretch in response to mouse drag, creating a kinetic shattered-glass effect with spring physics.',
  author: {
    name: "Aryan",
    imageUrl: 'https://pbs.twimg.com/profile_images/1927618320246919168/nvaCh-o8_400x400.jpg',
    redirectUrl: 'https://tarnished.lol'
  },
  tags: ['animated', 'interactive', 'text', 'distortion', 'hover-effects', 'canvas', 'spring-physics'],
  defaultProps: {
    text: 'DRAPES',
    fontSize: 280,
    fontFamily: 'Inter, sans-serif',
    textColor: '#f5f5f5',
    backgroundColor: '#0e0e0e',
    sliceHeight: 8,
    textOffsetX: 0,
    textOffsetY: 0,
    sensitivity: 1,
    stripWidth: 2,
    sliceGap: 0,
    enableGlitch: false,
    glitchIntensity: 1,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'text',
      label: 'Text',
      type: 'text-input',
      placeholder: 'Type your text...',
      maxLength: 20,
      defaultValue: 'DRAPES',
      description: 'The text displayed on the canvas.',
    },
    {
      key: 'fontSize',
      label: 'Font Size',
      type: 'slider',
      min: 60,
      max: 500,
      step: 10,
      defaultValue: 280,
      description: 'The size of the rendered text in pixels.',
    },
    {
      key: 'textColor',
      label: 'Text Color',
      type: 'color',
      defaultValue: '#f5f5f5',
      description: 'The color of the text.',
    },
    {
      key: 'backgroundColor',
      label: 'Background Color',
      type: 'color',
      defaultValue: '#0e0e0e',
      description: 'The background color of the canvas.',
    },
    {
      key: 'sliceHeight',
      label: 'Slice Height',
      type: 'slider',
      min: 2,
      max: 30,
      step: 1,
      defaultValue: 8,
      description: 'The height of each horizontal slice in pixels.',
    },
    {
      key: 'sensitivity',
      label: 'Sensitivity',
      type: 'slider',
      min: 0.1,
      max: 5,
      step: 0.1,
      defaultValue: 1,
      description: 'How strongly the slices react to mouse drag.',
    },
    {
      key: 'stripWidth',
      label: 'Strip Width',
      type: 'slider',
      min: 1,
      max: 20,
      step: 1,
      defaultValue: 2,
      description: 'The pixel width of each vertical strip column.',
    },
    {
      key: 'sliceGap',
      label: 'Slice Gap',
      type: 'slider',
      min: 0,
      max: 10,
      step: 1,
      defaultValue: 0,
      description: 'Gap between horizontal slices for a broken-mirror look.',
    },
    {
      key: 'textOffsetX',
      label: 'Text Offset X',
      type: 'slider',
      min: -500,
      max: 500,
      step: 10,
      defaultValue: 0,
      description: 'Horizontal offset of the text from center.',
    },
    {
      key: 'textOffsetY',
      label: 'Text Offset Y',
      type: 'slider',
      min: -300,
      max: 300,
      step: 10,
      defaultValue: 0,
      description: 'Vertical offset of the text from center.',
    },
    {
      key: 'enableGlitch',
      label: 'Enable Glitch',
      type: 'toggle',
      defaultValue: false,
      description: 'Activate RGB split & shake glitch effect on hover (disables kinetic distortion while active).',
    },
    {
      key: 'glitchIntensity',
      label: 'Glitch Intensity',
      type: 'slider',
      min: 0.1,
      max: 3,
      step: 0.1,
      defaultValue: 1,
      description: 'Controls the strength of the glitch effect (RGB split, displacement, shake).',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
