import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code';

export default {
  name: 'Chromatic Spiral',
  description: 'Hypnotic rotating spirals with a chromatic color shift effect',
  author: {
    name: "Ninjafire",
    imageUrl: 'https://pbs.twimg.com/profile_images/2006007847742758912/nWXptCKJ_400x400.jpg',
    redirectUrl: 'https://ninjafire.xyz'
  },
  tags: ['shader', 'webgl', 'animated', 'spiral', 'colorful'],
  defaultProps: {
    speed: 1.0,
    scale: 0.2,
    spiralDensity: 0.2,
    colorIntensity: 1.0,
    spiralTwist: 0.5,
    rotation: 0,
    translateX: 0,
    translateY: 0,
    backgroundColor: '#000000',
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'backgroundColor',
      label: 'Background',
      type: 'color',
      defaultValue: '#000000',
      description: 'Background color',
    },
    {
      key: 'speed',
      label: 'Speed',
      type: 'slider',
      min: 0.1,
      max: 3,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Animation speed',
    },
    {
      key: 'scale',
      label: 'Scale',
      type: 'slider',
      min: 0.05,
      max: 1.0,
      step: 0.05,
      defaultValue: 0.2,
      description: 'Overall zoom level',
    },
    {
      key: 'spiralDensity',
      label: 'Spiral Density',
      type: 'slider',
      min: 0.05,
      max: 0.5,
      step: 0.05,
      defaultValue: 0.2,
      description: 'Density of spiral arms',
    },
    {
      key: 'colorIntensity',
      label: 'Color Intensity',
      type: 'slider',
      min: 0.2,
      max: 2.0,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Vibrancy of colors',
    },
    {
      key: 'spiralTwist',
      label: 'Spiral Twist',
      type: 'slider',
      min: 0,
      max: 2.0,
      step: 0.1,
      defaultValue: 0.5,
      description: 'Amount of spiral twist',
    },
    {
      key: 'rotation',
      label: 'Rotation',
      type: 'slider',
      min: 0,
      max: 6.28,
      step: 0.1,
      defaultValue: 0,
      description: 'Rotation angle (radians)',
    },
    {
      key: 'translateX',
      label: 'Position X',
      type: 'slider',
      min: -5,
      max: 5,
      step: 0.1,
      defaultValue: 0,
      description: 'Horizontal position',
    },
    {
      key: 'translateY',
      label: 'Position Y',
      type: 'slider',
      min: -5,
      max: 5,
      step: 0.1,
      defaultValue: 0,
      description: 'Vertical position',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
