import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code';

export default {
  name: 'Background Tree',
  description: 'Realistic tree branch shadows spreading from the corner',
  author: {
    name: "Aryan",
    imageUrl: 'https://pbs.twimg.com/profile_images/1927618320246919168/nvaCh-o8_400x400.jpg',
    redirectUrl: 'https://tarnished.lol'
  },
  tags: ['canvas', '2d', 'animated', 'nature', 'shadows', 'tree', 'branches', 'organic'],
  defaultProps: {
    transparent: false,
    backgroundColor: '#e8e4e0',
    branchCount: 8,
    branchWidth: 1,
    shadowOpacity: 1,
    windStrength: 3,
    windSpeed: 2,
    position: 'top-left',
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'backgroundColor',
      label: 'Background Color',
      type: 'color',
      defaultValue: '#e8e4e0',
      description: 'Surface color behind the shadows',
    },
    {
      key: 'transparent',
      label: 'Transparent',
      type: 'toggle',
      defaultValue: true,
      description: 'Remove background fill for overlay use',
    },
    {
      key: 'branchCount',
      label: 'Branch Count',
      type: 'slider',
      min: 2,
      max: 12,
      step: 1,
      defaultValue: 8,
      description: 'Number of main branches from the corner',
    },
    {
      key: 'branchWidth',
      label: 'Branch Width',
      type: 'slider',
      min: 0.3,
      max: 3,
      step: 0.1,
      defaultValue: 1,
      description: 'Thickness multiplier for all branches',
    },
    {
      key: 'shadowOpacity',
      label: 'Shadow Opacity',
      type: 'slider',
      min: 0.2,
      max: 2,
      step: 0.1,
      defaultValue: 1,
      description: 'Darkness of branch shadows',
    },
    {
      key: 'windStrength',
      label: 'Wind Strength',
      type: 'slider',
      min: 0,
      max: 5,
      step: 0.1,
      defaultValue: 1,
      description: 'Intensity of wind sway on branches',
    },
    {
      key: 'windSpeed',
      label: 'Wind Speed',
      type: 'slider',
      min: 0.1,
      max: 5,
      step: 0.1,
      defaultValue: 0.8,
      description: 'Speed of wind animation',
    },
    {
      key: 'position',
      label: 'Position',
      type: 'select',
      options: ['top-right', 'top-left'],
      defaultValue: 'top-right',
      description: 'Corner where branches originate from',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
