import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code';

export default {
  name: 'Cyber Grid',
  description: 'A futuristic cyberpunk-style grid with glowing lines and distortion effects',
  author: {
    name: "Ninjafire",
    imageUrl: 'https://pbs.twimg.com/profile_images/2006007847742758912/nWXptCKJ_400x400.jpg',
    redirectUrl: 'https://ninjafire.xyz'
  },
  tags: ['shader', 'webgl2', 'animated', 'cyberpunk', 'grid'],
  defaultProps: {
    speed: 1.0,
    translateX: 0.0,
    translateY: 0.0,
    perspective: 4.0,
    depth: 3.0,
    gridDensity: 5.0,
    lineGlow: 0.2,
    distortion: 0.1,
    colorR: 1.0,
    colorG: 0.7,
    colorB: 0.6,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'speed',
      label: 'Speed',
      type: 'slider',
      min: 0.1,
      max: 3,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Animation speed',
    },
    {
      key: 'translateX',
      label: 'Translate X',
      type: 'slider',
      min: -4,
      max: 4,
      step: 0.1,
      defaultValue: 0.0,
      description: 'Horizontal offset of the grid',
    },
    {
      key: 'translateY',
      label: 'Translate Y',
      type: 'slider',
      min: -4,
      max: 4,
      step: 0.1,
      defaultValue: 0.0,
      description: 'Vertical offset of the grid',
    },
    {
      key: 'perspective',
      label: 'Perspective',
      type: 'slider',
      min: 1.0,
      max: 10.0,
      step: 0.5,
      defaultValue: 4.0,
      description: 'Perspective scaling of the grid',
    },
    {
      key: 'depth',
      label: 'Depth',
      type: 'slider',
      min: 1.0,
      max: 8.0,
      step: 0.5,
      defaultValue: 3.0,
      description: 'Vanishing point depth of the grid',
    },
    {
      key: 'gridDensity',
      label: 'Grid Density',
      type: 'slider',
      min: 1.0,
      max: 15.0,
      step: 0.5,
      defaultValue: 5.0,
      description: 'Density of the grid lines',
    },
    {
      key: 'lineGlow',
      label: 'Line Glow',
      type: 'slider',
      min: 0.05,
      max: 0.8,
      step: 0.05,
      defaultValue: 0.2,
      description: 'Brightness and thickness of grid lines',
    },
    {
      key: 'distortion',
      label: 'Distortion',
      type: 'slider',
      min: 0.01,
      max: 0.5,
      step: 0.01,
      defaultValue: 0.1,
      description: 'Frequency of the grid distortion effect',
    },
    {
      key: 'colorR',
      label: 'Color Red',
      type: 'slider',
      min: 0,
      max: 1.5,
      step: 0.05,
      defaultValue: 1.0,
      description: 'Red channel of the grid color',
    },
    {
      key: 'colorG',
      label: 'Color Green',
      type: 'slider',
      min: 0,
      max: 1.5,
      step: 0.05,
      defaultValue: 0.7,
      description: 'Green channel of the grid color',
    },
    {
      key: 'colorB',
      label: 'Color Blue',
      type: 'slider',
      min: 0,
      max: 1.5,
      step: 0.05,
      defaultValue: 0.6,
      description: 'Blue channel of the grid color',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
