import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code';

export default {
  name: 'Kaleidoscope',
  description: 'A vibrant kaleidoscope pattern with shifting colors and geometric symmetry',
  author: {
    name: "Aryan",
    imageUrl: 'https://pbs.twimg.com/profile_images/1927618320246919168/nvaCh-o8_400x400.jpg',
    redirectUrl: 'https://tarnished.lol'
  },
  tags: ['shader', 'webgl2', 'animated', 'colorful', 'geometric'],
  defaultProps: {
    speed: 1.0,
    backgroundColor: '#000000',
    zoom: 3,
    complexity: 5,
    intensity: 0.8,
    frequencyX: 0.6,
    frequencyY: 0.3,
    colorR: 0,
    colorG: 1,
    colorB: 2,
    softness: 0.9,
    rotation: 0,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'speed',
      label: 'Speed',
      type: 'slider',
      min: 0.1,
      max: 3,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Animation speed',
    },
    {
      key: 'backgroundColor',
      label: 'Background Color',
      type: 'color',
      defaultValue: '#000000',
      description: 'Background color drawn on canvas',
    },
    {
      key: 'zoom',
      label: 'Zoom',
      type: 'slider',
      min: 0.5,
      max: 8,
      step: 0.1,
      defaultValue: 3,
      description: 'Zoom level of the kaleidoscope',
    },
    {
      key: 'complexity',
      label: 'Complexity',
      type: 'slider',
      min: 1,
      max: 15,
      step: 0.5,
      defaultValue: 5,
      description: 'Pattern complexity of the kaleidoscope',
    },
    {
      key: 'intensity',
      label: 'Intensity',
      type: 'slider',
      min: 0.01,
      max: 2,
      step: 0.01,
      defaultValue: 0.8,
      description: 'Brightness intensity',
    },
    {
      key: 'frequencyX',
      label: 'Frequency X',
      type: 'slider',
      min: 0.1,
      max: 3,
      step: 0.05,
      defaultValue: 0.6,
      description: 'Horizontal pattern frequency',
    },
    {
      key: 'frequencyY',
      label: 'Frequency Y',
      type: 'slider',
      min: 0.1,
      max: 3,
      step: 0.05,
      defaultValue: 0.3,
      description: 'Vertical pattern frequency',
    },
    {
      key: 'colorR',
      label: 'Color Red',
      type: 'slider',
      min: 0,
      max: 4,
      step: 0.1,
      defaultValue: 0,
      description: 'Red channel offset',
    },
    {
      key: 'colorG',
      label: 'Color Green',
      type: 'slider',
      min: 0,
      max: 4,
      step: 0.1,
      defaultValue: 1,
      description: 'Green channel offset',
    },
    {
      key: 'colorB',
      label: 'Color Blue',
      type: 'slider',
      min: 0,
      max: 4,
      step: 0.1,
      defaultValue: 2,
      description: 'Blue channel offset',
    },
    {
      key: 'softness',
      label: 'Softness',
      type: 'slider',
      min: 0.1,
      max: 3,
      step: 0.1,
      defaultValue: 0.9,
      description: 'Edge softness of the pattern',
    },
    {
      key: 'rotation',
      label: 'Rotation',
      type: 'slider',
      min: 0,
      max: 6.28,
      step: 0.01,
      defaultValue: 0,
      description: 'Static rotation angle of the pattern (0 to 2π)',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
