import { BackgroundConfig } from '@/lib/types';
import { tsxCode, jsxCode, usageCode } from './code'

export default {
  id: '1',
  name: 'Wave Gradient',
  description: 'Smooth animated wave patterns with gradient colors',
  author: 'John',
  tags: ['animated', 'gradient', 'waves'],
  defaultProps: {
    color1: '#6366f1',
    color2: '#8b5cf6',
    amplitude: 50,
    frequency: 2,
    speed: 1,
    showWave: true,
    waveDirection: 'leftToRight',
    waveShape: 'sine',
  },
  code: {
    usage: usageCode,
    tsx: tsxCode,
    jsx: jsxCode
  },
  controls: [
    {
      key: 'color1',
      label: 'Primary Color',
      type: 'color',
      defaultValue: '#6366f1',
      description: 'Starting gradient color',
    },
    {
      key: 'color2',
      label: 'Secondary Color',
      type: 'color',
      defaultValue: '#8b5cf6',
      description: 'Ending gradient color',
    },
    {
      key: 'showWave',
      label: 'Show Wave',
      type: 'toggle',
      defaultValue: true,
      description: 'Toggle the wave overlay on/off',
    },
    {
      key: 'waveDirection',
      label: 'Wave Direction',
      type: 'select',
      options: ['leftToRight', 'rightToLeft'],
      defaultValue: 'leftToRight',
      description: 'Direction of wave animation flow',
    },
    {
      key: 'waveShape',
      label: 'Wave Shape',
      type: 'select',
      options: ['sine', 'cosine', 'triangle'],
      defaultValue: 'sine',
      description: 'Shape of the wave pattern',
    },
    {
      key: 'amplitude',
      label: 'Wave Height',
      type: 'slider',
      min: 10,
      max: 200,
      step: 5,
      defaultValue: 50,
      description: 'Shape of the wave pattern',
    },
    {
      key: 'frequency',
      label: 'Wave Frequency',
      type: 'slider',
      min: 0.5,
      max: 5,
      step: 0.1,
      defaultValue: 2,
      description: 'Shape of the wave pattern',
    },
    {
      key: 'speed',
      label: 'Animation Speed',
      type: 'slider',
      min: 0,
      max: 3,
      step: 0.1,
      description: 'Shape of the wave pattern',
      defaultValue: 1,
    },
  ],
} as BackgroundConfig;
