import { BackgroundConfig } from '@/lib/types';
import { tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code'

export default {
  name: 'Pipes',
  description: 'A futuristic animated background featuring glowing pipes that dynamically snake, turn, and flow across the screen with vibrant color shifts and smooth motion.',
  author: 'NetMods',
  tags: ['animated', 'pipes', 'flowing', 'futuristic', 'glowing', 'geometric', 'tron', 'neon'],
  defaultProps: {
    pipeCount: 50,
    backgroundColor: '#000000',
    baseSpeed: 0.5,
    rangeSpeed: 1,
    baseTTL: 300,
    rangeTTL: 600,
    baseWidth: 15,
    rangeWidth: 12,
    baseHue: 180,
    rangeHue: 60,
    turnCount: 8,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML
  },
  controls: [
    {
      key: 'backgroundColor',
      label: 'Background Color',
      type: 'color',
      defaultValue: '#000000',
      description: 'The dark canvas color that contrasts with the glowing pipes for a neon effect.',
    },
    {
      key: 'pipeCount',
      label: 'Pipe Count',
      type: 'slider',
      min: 10,
      max: 100,
      step: 10,
      defaultValue: 30,
      description: 'The number of active pipes animating simultaneously on the screen.',
    },
    {
      key: 'baseSpeed',
      label: 'Base Speed',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.1,
      defaultValue: 0.5,
      description: 'The foundational speed at which pipes extend and move across the background.',
    },
    {
      key: 'rangeSpeed',
      label: 'Speed Variation',
      type: 'slider',
      min: 0,
      max: 5,
      step: 1,
      defaultValue: 1,
      description: 'The range of speed differences to add dynamic variation to pipe movements.',
    },
    {
      key: 'baseTTL',
      label: 'Base Lifetime',
      type: 'slider',
      min: 0,
      max: 1000,
      step: 100,
      defaultValue: 300,
      description: 'The minimum duration a pipe remains visible before fading or resetting.',
    },
    {
      key: 'rangeTTL',
      label: 'Lifetime Variation',
      type: 'slider',
      min: 0,
      max: 1000,
      step: 100,
      defaultValue: 600,
      description: 'The range of lifetime differences for staggered pipe animations.',
    },
    {
      key: 'baseWidth',
      label: 'Base Width',
      type: 'slider',
      min: 0,
      max: 20,
      step: 1,
      defaultValue: 15,
      description: 'The standard thickness of each pipe segment.',
    },
    {
      key: 'rangeWidth',
      label: 'Width Variation',
      type: 'slider',
      min: 0,
      max: 20,
      step: 1,
      defaultValue: 12,
      description: 'The range of width differences to create varied pipe thicknesses.',
    },
    {
      key: 'baseHue',
      label: 'Base Hue',
      type: 'slider',
      min: 0,
      max: 300,
      step: 10,
      defaultValue: 180,
      description: 'The primary hue starting point for the pipes\' color gradient.',
    },
    {
      key: 'rangeHue',
      label: 'Hue Variation',
      type: 'slider',
      min: 0,
      max: 100,
      step: 10,
      defaultValue: 60,
      description: 'The hue range for shifting colors along the length of the pipes.',
    },
    {
      key: 'turnCount',
      label: 'Turn Count',
      type: 'slider',
      min: 0,
      max: 20,
      step: 1,
      defaultValue: 8,
      description: 'The number of smooth turns or bends each pipe makes during its animation cycle.',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
