import { BackgroundConfig } from '@/lib/types';
import { tsxCode, jsxCode, usageCode } from './code'

export default {
  id: '8',
  name: 'Pipelines',
  description: 'Smooth animated Snowfall',
  author: 'NetMods',
  tags: ['animated', 'gradient', 'waves'],
  thumbnail: '/thumbnails/wave-gradient.webp',
  defaultProps: {
    pipeCount: 30,
    backgroundColor: 'hsla(150,80%,1%,1)',
    baseSpeed: 0.5,
    rangeSpeed: 1,
    baseTTL: 300,
    rangeTTL: 600,
    baseWidth: 15,
    rangeWidth: 12,
    baseHue: 180,
    rangeHue: 60,
    turnCount: 8,
  },
  code: {
    usage: usageCode,
    tsx: tsxCode,
    jsx: jsxCode
  },
  controls: [
    {
      key: 'backgroundColor',
      label: 'background Color',
      type: 'color',
      defaultValue: 'hsla(150,80%,1%,1)',
      description: 'background Color',
    },
    {
      key: 'pipeCount',
      label: 'Pipe Count',
      type: 'slider',
      min: 10,
      max: 100,
      step: 10,
      defaultValue: 30,
    },
    {
      key: 'baseSpeed',
      label: 'Base Speed',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.1,
      defaultValue: 0.5,
    },
    {
      key: 'rangeSpeed',
      label: 'Range Speed',
      type: 'slider',
      min: 0,
      max: 5,
      step: 1,
      defaultValue: 1,
    },
    {
      key: 'baseTTL',
      label: 'baseTTL',
      type: 'slider',
      min: 0,
      max: 1000,
      step: 100,
      defaultValue: 300,
    },
    {
      key: 'rangeTTL',
      label: 'rangeTTL',
      type: 'slider',
      min: 0,
      max: 1000,
      step: 100,
      defaultValue: 600,
    },
    {
      key: 'baseWidth',
      label: 'Base Width',
      type: 'slider',
      min: 0,
      max: 20,
      step: 1,
      defaultValue: 15,
    },
    {
      key: 'rangeWidth',
      label: 'Range Width',
      type: 'slider',
      min: 0,
      max: 20,
      step: 1,
      defaultValue: 12,
    },
    {
      key: 'baseHue',
      label: 'Base Hue',
      type: 'slider',
      min: 0,
      max: 300,
      step: 10,
      defaultValue: 180,
    },
    {
      key: 'rangeHue',
      label: 'Range Hue',
      type: 'slider',
      min: 0,
      max: 100,
      step: 10,
      defaultValue: 60,
    },
    {
      key: 'turnCount',
      label: 'Turn Count',
      type: 'slider',
      min: 0,
      max: 20,
      step: 1,
      defaultValue: 8,
    },
  ],
} as BackgroundConfig;
