import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code'

export default {
  name: 'Cosmic Noise',
  description: 'Psychedelic animated fractal noise with vibrant shifting colors',
  author: {
    name: "Ninjafire",
    imageUrl: 'https://pbs.twimg.com/profile_images/2006007847742758912/nWXptCKJ_400x400.jpg',
    redirectUrl: 'https://ninjafire.xyz'
  },
  tags: ['animated', 'shader', 'noise', 'psychedelic', 'colorful'],
  defaultProps: {
    speed: 0.1,
    scale: 2.0,
    octaves: 7,
    colorFreqR: 10.0,
    colorFreqG: 11.0,
    colorFreqB: 12.0,
    colorOffsetR: 0.0,
    colorOffsetG: 2.0,
    colorOffsetB: 4.0,
    brightness: 0.5,
    saturation: 0.5,
    zoom: 1.0,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'speed',
      label: 'Speed',
      type: 'slider',
      min: 0.01,
      max: 0.5,
      step: 0.01,
      defaultValue: 0.1,
      description: 'Animation speed of the noise evolution',
    },
    {
      key: 'scale',
      label: 'Noise Scale',
      type: 'slider',
      min: 0.5,
      max: 5.0,
      step: 0.1,
      defaultValue: 2.0,
      description: 'Scale of the noise pattern — higher values create finer detail',
    },
    {
      key: 'octaves',
      label: 'Octaves',
      type: 'slider',
      min: 1,
      max: 7,
      step: 1,
      defaultValue: 7,
      description: 'Number of noise layers — more octaves add finer detail',
    },
    {
      key: 'zoom',
      label: 'Zoom',
      type: 'slider',
      min: 0.2,
      max: 3.0,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Zoom level of the effect',
    },
    {
      key: 'brightness',
      label: 'Brightness',
      type: 'slider',
      min: 0.0,
      max: 1.0,
      step: 0.05,
      defaultValue: 0.5,
      description: 'Overall brightness of the colors',
    },
    {
      key: 'saturation',
      label: 'Saturation',
      type: 'slider',
      min: 0.0,
      max: 1.0,
      step: 0.05,
      defaultValue: 0.5,
      description: 'Intensity of the color variation',
    },
    {
      key: 'colorFreqR',
      label: 'Red Frequency',
      type: 'slider',
      min: 1.0,
      max: 30.0,
      step: 0.5,
      defaultValue: 10.0,
      description: 'Frequency of the red color channel oscillation',
    },
    {
      key: 'colorFreqG',
      label: 'Green Frequency',
      type: 'slider',
      min: 1.0,
      max: 30.0,
      step: 0.5,
      defaultValue: 11.0,
      description: 'Frequency of the green color channel oscillation',
    },
    {
      key: 'colorFreqB',
      label: 'Blue Frequency',
      type: 'slider',
      min: 1.0,
      max: 30.0,
      step: 0.5,
      defaultValue: 12.0,
      description: 'Frequency of the blue color channel oscillation',
    },
    {
      key: 'colorOffsetR',
      label: 'Red Phase',
      type: 'slider',
      min: 0.0,
      max: 6.28,
      step: 0.1,
      defaultValue: 0.0,
      description: 'Phase offset for the red channel',
    },
    {
      key: 'colorOffsetG',
      label: 'Green Phase',
      type: 'slider',
      min: 0.0,
      max: 6.28,
      step: 0.1,
      defaultValue: 2.0,
      description: 'Phase offset for the green channel',
    },
    {
      key: 'colorOffsetB',
      label: 'Blue Phase',
      type: 'slider',
      min: 0.0,
      max: 6.28,
      step: 0.1,
      defaultValue: 4.0,
      description: 'Phase offset for the blue channel',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
