import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code'

export default {
  name: 'Dither Studio',
  description: 'A retro-style image and video processor that applies Bayer or Floyd-Steinberg dithering algorithms in real-time.',
  author: {
    name: "Ninjafire",
    imageUrl: 'https://pbs.twimg.com/profile_images/2006007847742758912/nWXptCKJ_400x400.jpg',
    redirectUrl: 'https://ninjafire.xyz'
  },
  tags: ['dithering', 'retro', 'canvas', 'image-processing', 'video', 'pixel-art'],
  defaultProps: {
    mediaType: 'image',
    ditherMode: 'bayer',
    isGrayscale: false,
    bayerLevel: 8,
    source: '/data/8251.jpg',
    brightness: 0,
    contrast: 0,
    highlights: 0,
    midtones: 0,
    blur: 0,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'mediaType',
      label: 'Media Type',
      type: 'select',
      options: ['image', 'video'],
      defaultValue: 'image',
      description: 'Choose between processing a static image or a looping video.',
    },
    {
      key: 'ditherMode',
      label: 'Dither Algorithm',
      type: 'select',
      options: ['none', 'bayer', 'floyd'],
      defaultValue: 'bayer',
      description: 'Select the dithering method (Bayer for patterns, Floyd for smooth diffusion).',
    },
    {
      key: 'bayerLevel',
      label: 'Bayer Matrix Level',
      type: 'select',
      options: [2, 4, 8, 16],
      defaultValue: 8,
      description: 'Determines the density of the Bayer dithering pattern.',
    },
    {
      key: 'source',
      label: 'Media Source',
      type: 'media-input',
      defaultValue: '/data/8251.jpg',
      defaultImage: '/data/8251.jpg',
      defaultVideo: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
      description: 'Upload an image or video file to apply dithering effects.',
      mediaTypeKey: 'mediaType',
    },
    {
      key: 'isGrayscale',
      label: 'Grayscale Mode',
      type: 'toggle',
      defaultValue: false,
      description: 'Convert the output to black and white.',
    },
    {
      key: 'brightness',
      label: 'Brightness',
      type: 'slider',
      min: -100,
      max: 100,
      step: 1,
      defaultValue: 0,
      description: 'Adjust the luminance of the source before dithering.',
    },
    {
      key: 'contrast',
      label: 'Contrast',
      type: 'slider',
      min: -100,
      max: 100,
      step: 1,
      defaultValue: 0,
      description: 'Adjust the difference between light and dark areas.',
    },
    {
      key: 'midtones',
      label: 'Midtones (Gamma)',
      type: 'slider',
      min: -100,
      max: 100,
      step: 1,
      defaultValue: 0,
      description: 'Adjust the gamma/midrange of the image.',
    },
    {
      key: 'highlights',
      label: 'Highlights',
      type: 'slider',
      min: -100,
      max: 100,
      step: 1,
      defaultValue: 0,
      description: 'Adjust the intensity of the brightest areas of the media.',
    },
    {
      key: 'blur',
      label: 'Pre-Process Blur',
      type: 'slider',
      min: 0,
      max: 20,
      step: 1,
      defaultValue: 0,
      description: 'Apply a blur before dithering to soften high-frequency details.',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
