import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code'
export default {
  name: 'Dither Studio',
  description: 'A retro-style image and video processor that applies Bayer or Floyd-Steinberg dithering algorithms in real-time.',
  author: {
    name: "Ninjafire",
    imageUrl: 'https://pbs.twimg.com/profile_images/2006007847742758912/nWXptCKJ_400x400.jpg',
    redirectUrl: 'https://ninjafire.xyz'
  },
  tags: ['dithering', 'retro', 'canvas', 'image-processing', 'video', 'pixel-art'],
  defaultProps: {
    mediaType: 'image',
    ditherMode: 'bayer',
    colorTheme: 'colorful',
    bayerLevel: 8,
    source: '/data/vegeta.png',
    brightness: 0,
    contrast: 0,
    highlights: 0,
    midtones: 0,
    blur: 0,
    objectFit: 'cover',
    pixelSize: 2,
    mouseInteraction: false,
    mouseRadius: 100,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'mediaType',
      label: 'Media Type',
      type: 'select',
      options: ['image', 'video'],
      defaultValue: 'image',
      description: 'Choose between processing a static image or a looping video.',
    },
    {
      key: 'source',
      label: 'Media Source',
      type: 'media-input',
      defaultValue: '/data/vegeta.png',
      defaultImage: '/data/vegeta.png',
      defaultVideo: '/data/vegeta.mp4',
      description: 'Upload an image or video file to apply dithering effects.',
      mediaTypeKey: 'mediaType',
    },
    {
      key: 'objectFit',
      label: 'Object Fit',
      type: 'select',
      options: ['contain', 'cover', 'fill'],
      defaultValue: 'cover',
      description: 'Control how the media fits within the canvas (contain, cover, or fill).',
    },
    {
      key: 'ditherMode',
      label: 'Dither Algorithm',
      type: 'select',
      options: ['none', 'bayer', 'floyd'],
      defaultValue: 'bayer',
      description: 'Select the dithering method (Bayer for patterns, Floyd for smooth diffusion).',
    },
    {
      key: 'bayerLevel',
      label: 'Bayer Matrix Level',
      type: 'select',
      options: [2, 4, 8, 16],
      defaultValue: 8,
      description: 'Determines the density of the Bayer dithering pattern.',
    },
    {
      key: 'colorTheme',
      label: 'Color Theme',
      type: 'select',
      options: ['colorful', 'monochrome', 'ink-paper', 'amber-glow', 'game-boy', 'nes', 'terminal', 'blueprint', 'neon-punk'],
      defaultValue: 'colorful',
      description: 'Choose a color theme for the dithered output.',
    },
    {
      key: 'pixelSize',
      label: 'Pixel Size',
      type: 'slider',
      min: 1,
      max: 32,
      step: 1,
      defaultValue: 4,
      description: 'Control the size of rendered pixels.',
    },
    {
      key: 'mouseInteraction',
      label: 'Mouse Reveal',
      type: 'toggle',
      defaultValue: false,
      description: 'Hover over the image to reveal a less-dithered version through a soft circular area.',
    },
    {
      key: 'mouseRadius',
      label: 'Reveal Radius',
      type: 'slider',
      min: 30,
      max: 300,
      step: 5,
      defaultValue: 100,
      description: 'Control the size of the mouse reveal circle.',
    },
    {
      key: 'brightness',
      label: 'Brightness',
      type: 'slider',
      min: -100,
      max: 100,
      step: 1,
      defaultValue: 0,
      description: 'Adjust the luminance of the source before dithering.',
    },
    {
      key: 'contrast',
      label: 'Contrast',
      type: 'slider',
      min: -100,
      max: 100,
      step: 1,
      defaultValue: 0,
      description: 'Adjust the difference between light and dark areas.',
    },
    {
      key: 'midtones',
      label: 'Midtones (Gamma)',
      type: 'slider',
      min: -100,
      max: 100,
      step: 1,
      defaultValue: 0,
      description: 'Adjust the gamma/midrange of the image.',
    },
    {
      key: 'highlights',
      label: 'Highlights',
      type: 'slider',
      min: -100,
      max: 100,
      step: 1,
      defaultValue: 0,
      description: 'Adjust the intensity of the brightest areas of the media.',
    },
    {
      key: 'blur',
      label: 'Pre-Process Blur',
      type: 'slider',
      min: 0,
      max: 20,
      step: 1,
      defaultValue: 0,
      description: 'Apply a blur before dithering to soften high-frequency details.',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
