import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code';

export default {
  name: 'Mosaic Flow',
  description: 'A colorful mosaic pattern that scrolls with a painted, artistic aesthetic',
  author: {
    name: "Aryan",
    imageUrl: 'https://pbs.twimg.com/profile_images/1927618320246919168/nvaCh-o8_400x400.jpg',
    redirectUrl: 'https://tarnished.lol'
  },
  tags: ['shader', 'webgl', 'animated', 'colorful', 'mosaic'],
  defaultProps: {
    speed: 1.0,
    scale: 0.1,
    tileSize: 3.0,
    perspective: 3.0,
    colorIntensity: 1.0,
    noiseFrequency: 7000.0,
    rotation: 0,
    translateX: 0,
    translateY: 0,
    backgroundColor: '#000000',
    primaryColor: '#8c00ff',
    secondaryColor: '#00eaff',
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'backgroundColor',
      label: 'Background',
      type: 'color',
      defaultValue: '#000000',
      description: 'Background color',
    },
    {
      key: 'primaryColor',
      label: 'Primary Color',
      type: 'color',
      defaultValue: '#8c00ff',
      description: 'Main gradient color',
    },
    {
      key: 'secondaryColor',
      label: 'Secondary Color',
      type: 'color',
      defaultValue: '#00eaff',
      description: 'Secondary gradient color',
    },
    {
      key: 'speed',
      label: 'Speed',
      type: 'slider',
      min: 0.1,
      max: 3,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Animation speed',
    },
    {
      key: 'scale',
      label: 'Scale',
      type: 'slider',
      min: 0.05,
      max: 0.5,
      step: 0.01,
      defaultValue: 0.1,
      description: 'Tile scale factor',
    },
    {
      key: 'tileSize',
      label: 'Tile Size',
      type: 'slider',
      min: 1.0,
      max: 10.0,
      step: 0.5,
      defaultValue: 3.0,
      description: 'Size of mosaic tiles',
    },
    {
      key: 'perspective',
      label: 'Perspective',
      type: 'slider',
      min: 1.0,
      max: 10.0,
      step: 0.5,
      defaultValue: 3.0,
      description: 'Depth perspective amount',
    },
    {
      key: 'colorIntensity',
      label: 'Color Intensity',
      type: 'slider',
      min: 0.1,
      max: 2.0,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Brightness/Vibrancy of colors',
    },
    {
      key: 'noiseFrequency',
      label: 'Noise',
      type: 'slider',
      min: 1000,
      max: 15000,
      step: 500,
      defaultValue: 7000,
      description: 'Color noise frequency',
    },
    {
      key: 'rotation',
      label: 'Rotation',
      type: 'slider',
      min: 0,
      max: 6.28,
      step: 0.1,
      defaultValue: 0,
      description: 'Rotation angle (radians)',
    },
    {
      key: 'translateX',
      label: 'Position X',
      type: 'slider',
      min: -2,
      max: 2,
      step: 0.1,
      defaultValue: 0,
      description: 'Horizontal position',
    },
    {
      key: 'translateY',
      label: 'Position Y',
      type: 'slider',
      min: -2,
      max: 2,
      step: 0.1,
      defaultValue: 0,
      description: 'Vertical position',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
