import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code';

export default {
  name: 'Nebula',
  description: 'A swirling cosmic nebula with volumetric particle clouds and ethereal glow',
  author: {
    name: "Aryan",
    imageUrl: 'https://pbs.twimg.com/profile_images/1927618320246919168/nvaCh-o8_400x400.jpg',
    redirectUrl: 'https://tarnished.lol'
  },
  tags: ['shader', 'webgl', 'animated', 'space', 'particles'],
  defaultProps: {
    speed: 1.0,
    brightness: 1.0,
    translateX: 0.0,
    translateY: 0.0,
    scale: 1.0,
    density: 0.1,
    turbulence: 0.5,
    intensity: 0.2,
    colorR: 1.0,
    colorG: 1.0,
    colorB: 1.0,
    renderScale: 0.6,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'speed',
      label: 'Speed',
      type: 'slider',
      min: 0.1,
      max: 3,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Animation speed',
    },
    {
      key: 'brightness',
      label: 'Brightness',
      type: 'slider',
      min: 0.2,
      max: 2,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Overall brightness of the nebula',
    },
    {
      key: 'translateX',
      label: 'Translate X',
      type: 'slider',
      min: -3,
      max: 3,
      step: 0.1,
      defaultValue: 0.0,
      description: 'Horizontal offset of the nebula',
    },
    {
      key: 'translateY',
      label: 'Translate Y',
      type: 'slider',
      min: -3,
      max: 3,
      step: 0.1,
      defaultValue: 0.0,
      description: 'Vertical offset of the nebula',
    },
    {
      key: 'scale',
      label: 'Scale',
      type: 'slider',
      min: 0.3,
      max: 3.0,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Zoom level of the nebula',
    },
    {
      key: 'density',
      label: 'Density',
      type: 'slider',
      min: 0.02,
      max: 0.3,
      step: 0.01,
      defaultValue: 0.1,
      description: 'Cloud density and pattern granularity',
    },
    {
      key: 'turbulence',
      label: 'Turbulence',
      type: 'slider',
      min: 0.1,
      max: 1.5,
      step: 0.05,
      defaultValue: 0.5,
      description: 'Swirl and distortion of the nebula clouds',
    },
    {
      key: 'intensity',
      label: 'Intensity',
      type: 'slider',
      min: 0.05,
      max: 0.5,
      step: 0.01,
      defaultValue: 0.2,
      description: 'Light accumulation per ray step',
    },
    {
      key: 'colorR',
      label: 'Color Red',
      type: 'slider',
      min: 0,
      max: 1.5,
      step: 0.05,
      defaultValue: 1.0,
      description: 'Red channel of the nebula color',
    },
    {
      key: 'colorG',
      label: 'Color Green',
      type: 'slider',
      min: 0,
      max: 1.5,
      step: 0.05,
      defaultValue: 1.0,
      description: 'Green channel of the nebula color',
    },
    {
      key: 'colorB',
      label: 'Color Blue',
      type: 'slider',
      min: 0,
      max: 1.5,
      step: 0.05,
      defaultValue: 1.0,
      description: 'Blue channel of the nebula color',
    },
    {
      key: 'renderScale',
      label: 'Render Scale',
      type: 'slider',
      min: 0.1,
      max: 1.0,
      step: 0.05,
      defaultValue: 0.6,
      description: 'Resolution scale factor (lower = better performance)',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
