import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code'

export default {
  name: 'ASCII Studio',
  description: 'A real-time ASCII art renderer that converts images and videos into text-based art using various character sets.',
  author: {
    name: "Ninjafire",
    imageUrl: 'https://pbs.twimg.com/profile_images/2006007847742758912/nWXptCKJ_400x400.jpg',
    redirectUrl: 'https://ninjafire.xyz'
  },
  tags: ['ascii', 'retro', 'canvas', 'image-processing', 'video', 'text-art', 'terminal'],
  defaultProps: {
    mediaType: 'image',
    asciiMode: 'standard',
    source: '/data/zoro.jpg',
    objectFit: 'cover',
    fontSize: 14,
    colorTheme: 'colorful',
    filledBlocks: true,
    contrast: 0,
    highlights: 0,
    midtones: 0,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'mediaType',
      label: 'Media Type',
      type: 'select',
      options: ['image', 'video'],
      defaultValue: 'image',
      description: 'Choose between processing a static image or a looping video.',
    },
    {
      key: 'source',
      label: 'Media Source',
      type: 'media-input',
      defaultValue: '/data/zoro.jpg',
      defaultImage: '/data/zoro.jpg',
      defaultVideo: '/data/zoro.mp4',
      description: 'Upload an image or video file to convert to ASCII art.',
      mediaTypeKey: 'mediaType',
    },
    {
      key: 'objectFit',
      label: 'Object Fit',
      type: 'select',
      options: ['contain', 'cover', 'fill'],
      defaultValue: 'cover',
      description: 'Control how the media fits within the canvas (contain, cover, or fill).',
    },
    {
      key: 'asciiMode',
      label: 'ASCII Style',
      type: 'select',
      options: ['standard', 'technical', 'dense', 'minimal', 'blocks', 'braille', 'hatching'],
      defaultValue: 'standard',
      description: 'Select the character set for ASCII rendering.',
    },
    {
      key: 'fontSize',
      label: 'Character Size',
      type: 'slider',
      min: 4,
      max: 24,
      step: 1,
      defaultValue: 14,
      description: 'Adjust the size of ASCII characters (smaller = more detail).',
    },
    {
      key: 'colorTheme',
      label: 'Color Theme',
      type: 'select',
      options: ['colorful', 'monochrome', 'ink-paper', 'amber-glow', 'game-boy', 'nes', 'terminal', 'blueprint', 'neon-punk'],
      defaultValue: 'colorful',
      description: 'Choose a color theme for the ASCII output.',
    },
    {
      key: 'filledBlocks',
      label: 'Filled Blocks',
      type: 'toggle',
      defaultValue: true,
      description: 'Toggle between colored blocks with character cutouts and colored characters on background.',
    },
    {
      key: 'contrast',
      label: 'Contrast',
      type: 'slider',
      min: -100,
      max: 100,
      step: 1,
      defaultValue: 0,
      description: 'Adjust the difference between light and dark areas.',
    },
    {
      key: 'midtones',
      label: 'Midtones (Gamma)',
      type: 'slider',
      min: -100,
      max: 100,
      step: 1,
      defaultValue: 0,
      description: 'Adjust the gamma/midrange of the image.',
    },
    {
      key: 'highlights',
      label: 'Highlights',
      type: 'slider',
      min: -100,
      max: 100,
      step: 1,
      defaultValue: 0,
      description: 'Adjust the intensity of the brightest areas of the media.',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
