import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code'

export default {
  name: 'Bitmap Noise',
  description: 'A retro-style, shader-based bitmap noise effect powered by WebGL with 3D rotation support.',
  author: {
    name: "Aryan",
    imageUrl: 'https://pbs.twimg.com/profile_images/1927618320246919168/nvaCh-o8_400x400.jpg',
    redirectUrl: 'https://tarnished.lol'
  },
  tags: ['webgl', 'shader', 'noise', 'retro', 'glitch', 'background', 'abstract', '3d', 'rotation'],
  defaultProps: {
    scale: 0.1,
    speed: 1.0,
    distortion: 5.0,
    rotationX: 0.0,
    rotationY: 0.0,
    rotationZ: 0.0,
    autoRotate: false,
    autoRotateSpeed: 1.0,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'scale',
      label: 'Scale',
      type: 'slider',
      min: 0.05,
      max: 1.0,
      step: 0.01,
      defaultValue: 0.1,
      description: 'Controls the zoom level of the noise pattern. Lower values create larger blocks.',
    },
    {
      key: 'speed',
      label: 'Speed',
      type: 'slider',
      min: 0,
      max: 5.0,
      step: 0.1,
      defaultValue: 1.0,
      description: 'The horizontal movement speed of the noise.',
    },
    {
      key: 'distortion',
      label: 'Distortion',
      type: 'slider',
      min: 0,
      max: 20.0,
      step: 0.5,
      defaultValue: 5.0,
      description: 'The intensity of the sine-wave distortion applied to the grid.',
    },
    {
      key: 'rotationX',
      label: 'Rotation X',
      type: 'slider',
      min: -Math.PI,
      max: Math.PI,
      step: 0.01,
      defaultValue: 0.0,
      description: 'Rotation around the X axis in radians. Tilts the pattern forward/backward.',
    },
    {
      key: 'rotationY',
      label: 'Rotation Y',
      type: 'slider',
      min: -Math.PI,
      max: Math.PI,
      step: 0.01,
      defaultValue: 0.0,
      description: 'Rotation around the Y axis in radians. Rotates the pattern left/right.',
    },
    {
      key: 'rotationZ',
      label: 'Rotation Z',
      type: 'slider',
      min: -Math.PI,
      max: Math.PI,
      step: 0.01,
      defaultValue: 0.0,
      description: 'Rotation around the Z axis in radians. Spins the pattern clockwise/counter-clockwise.',
    },
    {
      key: 'autoRotate',
      label: 'Auto Rotate',
      type: 'toggle',
      defaultValue: false,
      description: 'Enable automatic continuous rotation animation.',
    },
    {
      key: 'autoRotateSpeed',
      label: 'Auto Rotate Speed',
      type: 'slider',
      min: 0.1,
      max: 5.0,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Speed multiplier for the auto-rotation animation.',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
