import { BackgroundConfig } from '@/lib/types';
import { tsxCode, jsxCode, usageCode } from './code'
export default {
  id: '5',
  name: 'Spirals',
  description: 'A hypnotic animated background of mathematical spirals that elegantly spin and expand with smooth rotation, customizable for velocity, colors, and spacing to create mesmerizing geometric flows.',
  author: 'NetMods',
  tags: ['animated', 'spirals', 'mathematical', 'rotation', 'hypnotic', 'geometric', 'flow', 'abstract'],
  defaultProps: {
    maxOffset: 400,
    spacing: 3,
    pointsPerLap: 6,
    shadowStrength: 6,
    primaryColor: '#ffffff',
    secondaryColor: '#ffffff',
    lineWidth: 2,
    initialVelocity: 0.1,
  },
  code: {
    usage: usageCode,
    tsx: tsxCode,
    jsx: jsxCode
  },
  controls: [
    {
      key: 'primaryColor',
      label: 'Primary Color',
      type: 'color',
      defaultValue: '#ffffff',
      description: 'The main stroke color defining the visible lines of the spinning spirals.',
    },
    {
      key: 'secondaryColor',
      label: 'Secondary Color',
      type: 'color',
      defaultValue: '#ffffff',
      description: 'The shadow or accent color that adds depth and glow to the spiral patterns.',
    },
    {
      key: 'maxOffset',
      label: 'Max Offset',
      type: 'slider',
      min: 10,
      max: 1000,
      step: 50,
      defaultValue: 400,
      description: 'The maximum radial offset determining the overall size and reach of the spirals.',
    },
    {
      key: 'spacing',
      label: 'Spacing',
      type: 'slider',
      min: 3,
      max: 10,
      step: 1,
      defaultValue: 3,
      description: 'The angular spacing between points along each spiral arm for density control.',
    },
    {
      key: 'lineWidth',
      label: 'Line Width',
      type: 'slider',
      min: 1,
      max: 10,
      step: 1,
      defaultValue: 2,
      description: 'The thickness of the spiral lines to adjust visual weight and prominence.',
    },
    {
      key: 'initialVelocity',
      label: 'Initial Velocity',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.1,
      defaultValue: 0.1,
      description: 'The starting rotational speed influencing how quickly the spirals spin and evolve.',
    },
  ],
} as BackgroundConfig;
