import { BackgroundConfig } from '@/lib/types';
import { tsxCode, jsxCode, usageCode } from './code'
import { tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code'

export default {
  name: 'Particles',
  description: 'An enchanting interactive background of smooth animated confetti particles that gracefully follow your mouse cursor, creating dynamic trails influenced by gravity and speed.',
  author: 'NetMods',
  tags: ['animated', 'confetti', 'particles', 'mouse-follow', 'interactive', 'trails', 'gravity', 'celebratory'],
  defaultProps: {
    numConfetti: 350,
    minRadius: 2,
    maxRadius: 6,
    minSpeed: 1,
    maxSpeed: 1,
    gravity: 0.7,
    fadeSpeed: 0.03,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML
  },
  controls: [
    {
      key: 'numConfetti',
      label: 'Number of Confetti',
      type: 'slider',
      min: 10,
      max: 1000,
      step: 20,
      defaultValue: 350,
      description: 'The total quantity of confetti particles animating across the background.',
    },
    {
      key: 'minRadius',
      label: 'Min Radius',
      type: 'slider',
      min: 1,
      max: 10,
      step: 1,
      defaultValue: 2,
      description: 'The smallest size radius for individual confetti particles.',
    },
    {
      key: 'maxRadius',
      label: 'Max Radius',
      type: 'slider',
      min: 1,
      max: 10,
      step: 1,
      defaultValue: 6,
      description: 'The largest size radius for individual confetti particles.',
    },
    {
      key: 'minSpeed',
      label: 'Min Speed',
      type: 'slider',
      min: 1,
      max: 20,
      step: 1,
      defaultValue: 1,
      description: 'The minimum velocity applied to confetti particles during movement.',
    },
    {
      key: 'maxSpeed',
      label: 'Max Speed',
      type: 'slider',
      min: 1,
      max: 20,
      step: 1,
      defaultValue: 1,
      description: 'The maximum velocity applied to confetti particles during movement.',
    },
    {
      key: 'gravity',
      label: 'Gravity',
      type: 'slider',
      min: 1,
      max: 2,
      step: 0.1,
      defaultValue: 0.7,
      description: 'The gravitational force pulling confetti particles downward for realistic motion.',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
