import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code';

export default {
  name: 'Horizon Glow',
  description: 'A WebGL-powered atmospheric light horizon with dynamic intensity, fluid movement, and shader-based background control.',
  author: {
    name: "Aryan",
    imageUrl: 'https://pbs.twimg.com/profile_images/1927618320246919168/nvaCh-o8_400x400.jpg',
    redirectUrl: 'https://tarnished.lol'
  },
  tags: ['webgl', 'gradient', 'glow', 'abstract', 'atmosphere', 'neon', 'shader'],
  defaultProps: {
    speed: 0.5,
    backgroundColor: '#000000',
    frequency: 1.0,
    amplitude: 0.2,
    intensity: 0.13,
    rotation: 0,
    translateX: 0,
    translateY: 0,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'backgroundColor',
      label: 'Background Color',
      type: 'color',
      defaultValue: '#000000',
      description: 'The base background color rendered directly by the shader.',
    },
    {
      key: 'speed',
      label: 'Flow Speed',
      type: 'slider',
      min: 0,
      max: 5.0,
      step: 0.1,
      defaultValue: 0.5,
      description: 'The speed of the time-based undulation.',
    },
    {
      key: 'frequency',
      label: 'Wave Frequency',
      type: 'slider',
      min: 0.0,
      max: 10.0,
      step: 0.1,
      defaultValue: 2.0,
      description: 'Controls the density/tightness of the horizontal waves.',
    },
    {
      key: 'amplitude',
      label: 'Wave Amplitude',
      type: 'slider',
      min: 0.0,
      max: 2.0,
      step: 0.01,
      defaultValue: 0.4,
      description: 'Controls the vertical height of the wave peaks.',
    },
    {
      key: 'intensity',
      label: 'Glow Intensity',
      type: 'slider',
      min: 0.01,
      max: 0.4,
      step: 0.01,
      defaultValue: 0.13,
      description: 'The brightness and thickness of the horizon line.',
    },
    {
      key: 'rotation',
      label: 'Rotation (Deg)',
      type: 'slider',
      min: 0,
      max: 360,
      step: 1,
      defaultValue: 0,
      description: 'Rotates the entire coordinate system.',
    },
    {
      key: 'translateX',
      label: 'Position X',
      type: 'slider',
      min: -2.0,
      max: 2.0,
      step: 0.05,
      defaultValue: 0,
      description: 'Move the horizon horizontally (-1 to 1 is screen width).',
    },
    {
      key: 'translateY',
      label: 'Position Y',
      type: 'slider',
      min: -2.0,
      max: 2.0,
      step: 0.05,
      defaultValue: 0,
      description: 'Move the horizon vertically (-1 to 1 is screen height).',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
