import { BackgroundConfig } from '@/lib/types';
import { tsxCode, jsxCode, usageCode } from './code';

export default {
  name: 'Plasma Waves',
  description: 'Retro-futuristic animated plasma waves with customizable neon effects',
  author: 'NetMods',
  tags: ['animated', 'shader', 'synthwave', 'retro', 'neon'],
  defaultProps: {
    overallSpeed: 0.2,
    lineSpeed: 1.0,
    warpSpeed: 0.2,
    offsetSpeed: 1.33,
    gridSmoothWidth: 0.015,
    axisWidth: 0.05,
    majorLineWidth: 0.025,
    minorLineWidth: 0.0125,
    majorLineFrequency: 5.0,
    minorLineFrequency: 1.0,
    minLineWidth: 0.01,
    maxLineWidth: 0.2,
    lineAmplitude: 1.0,
    lineFrequency: 0.2,
    linesPerGroup: 16,
    warpFrequency: 0.5,
    warpAmplitude: 1.0,
    offsetFrequency: 0.5,
    minOffsetSpread: 0.6,
    maxOffsetSpread: 2.0,
    lineColorR: 0.4,
    lineColorG: 0.2,
    lineColorB: 0.8,
    lineColorA: 1.0,
    bgColor1R: 0.1,
    bgColor1G: 0.1,
    bgColor1B: 0.3,
    bgColor1A: 1.0,
    bgColor2R: 0.3,
    bgColor2G: 0.1,
    bgColor2B: 0.5,
    bgColor2A: 1.0,
    scale: 5.0,
  },
  code: {
    usage: usageCode,
    tsx: tsxCode,
    jsx: jsxCode,
  },
  controls: [
    {
      key: 'overallSpeed',
      label: 'Overall Speed',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.05,
      defaultValue: 0.2,
      description: 'Master speed multiplier for all animations',
    },
    {
      key: 'lineSpeed',
      label: 'Line Speed',
      type: 'slider',
      min: 0,
      max: 3,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Speed of wave line movement',
    },
    {
      key: 'warpSpeed',
      label: 'Warp Speed',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.05,
      defaultValue: 0.2,
      description: 'Speed of space warping effect',
    },
    {
      key: 'offsetSpeed',
      label: 'Offset Speed',
      type: 'slider',
      min: 0,
      max: 3,
      step: 0.1,
      defaultValue: 1.33,
      description: 'Speed of line offset animation',
    },

    // Line Properties
    {
      key: 'linesPerGroup',
      label: 'Line Count',
      type: 'slider',
      min: 4,
      max: 32,
      step: 2,
      defaultValue: 16,
      description: 'Number of plasma lines',
    },
    {
      key: 'minLineWidth',
      label: 'Min Line Width',
      type: 'slider',
      min: 0.005,
      max: 0.05,
      step: 0.005,
      defaultValue: 0.01,
      description: 'Minimum thickness of lines',
    },
    {
      key: 'maxLineWidth',
      label: 'Max Line Width',
      type: 'slider',
      min: 0.05,
      max: 0.5,
      step: 0.05,
      defaultValue: 0.2,
      description: 'Maximum thickness of lines',
    },
    {
      key: 'lineAmplitude',
      label: 'Wave Amplitude',
      type: 'slider',
      min: 0,
      max: 3,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Height of wave oscillations',
    },
    {
      key: 'lineFrequency',
      label: 'Wave Frequency',
      type: 'slider',
      min: 0.1,
      max: 1,
      step: 0.05,
      defaultValue: 0.2,
      description: 'Frequency of wave oscillations',
    },

    // Warp Effect
    {
      key: 'warpFrequency',
      label: 'Warp Frequency',
      type: 'slider',
      min: 0.1,
      max: 2,
      step: 0.1,
      defaultValue: 0.5,
      description: 'Frequency of space distortion',
    },
    {
      key: 'warpAmplitude',
      label: 'Warp Amplitude',
      type: 'slider',
      min: 0,
      max: 3,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Intensity of space distortion',
    },

    // Offset Properties
    {
      key: 'offsetFrequency',
      label: 'Offset Frequency',
      type: 'slider',
      min: 0.1,
      max: 2,
      step: 0.1,
      defaultValue: 0.5,
      description: 'Frequency of line offset variation',
    },
    {
      key: 'minOffsetSpread',
      label: 'Min Offset Spread',
      type: 'slider',
      min: 0,
      max: 2,
      step: 0.1,
      defaultValue: 0.6,
      description: 'Minimum vertical spread of lines',
    },
    {
      key: 'maxOffsetSpread',
      label: 'Max Offset Spread',
      type: 'slider',
      min: 1,
      max: 5,
      step: 0.1,
      defaultValue: 2.0,
      description: 'Maximum vertical spread of lines',
    },

    // Visual Scale
    {
      key: 'scale',
      label: 'Zoom Scale',
      type: 'slider',
      min: 1,
      max: 15,
      step: 0.5,
      defaultValue: 10.0,
      description: 'Overall zoom level of the effect',
    },

    // Grid Properties (Advanced)
    {
      key: 'gridSmoothWidth',
      label: 'Grid Smooth Width',
      type: 'slider',
      min: 0.005,
      max: 0.05,
      step: 0.005,
      defaultValue: 0.015,
      description: 'Smoothness of grid lines',
    },
    {
      key: 'axisWidth',
      label: 'Axis Width',
      type: 'slider',
      min: 0.01,
      max: 0.1,
      step: 0.01,
      defaultValue: 0.05,
      description: 'Width of main axis lines',
    },
    {
      key: 'majorLineWidth',
      label: 'Major Grid Line Width',
      type: 'slider',
      min: 0.01,
      max: 0.1,
      step: 0.005,
      defaultValue: 0.025,
      description: 'Width of major grid lines',
    },
    {
      key: 'minorLineWidth',
      label: 'Minor Grid Line Width',
      type: 'slider',
      min: 0.005,
      max: 0.05,
      step: 0.005,
      defaultValue: 0.0125,
      description: 'Width of minor grid lines',
    },
    {
      key: 'majorLineFrequency',
      label: 'Major Grid Frequency',
      type: 'slider',
      min: 1,
      max: 10,
      step: 1,
      defaultValue: 5.0,
      description: 'Spacing of major grid lines',
    },
    {
      key: 'minorLineFrequency',
      label: 'Minor Grid Frequency',
      type: 'slider',
      min: 0.5,
      max: 5,
      step: 0.5,
      defaultValue: 1.0,
      description: 'Spacing of minor grid lines',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
