import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code';

export default {
  name: 'Game of Life',
  description: "Conway's Game of Life simulation running as an animated background, with mouse interaction to spawn cells.",
  author: {
    name: 'Aryan',
    imageUrl: 'https://pbs.twimg.com/profile_images/1927618320246919168/nvaCh-o8_400x400.jpg',
    redirectUrl: 'https://tarnished.lol',
  },
  tags: ['animated', 'cellular-automata', 'interactive', 'minimal', 'light'],
  defaultProps: {
    backgroundColor: '#ffffff',
    cellColor: '#22c55e',
    cellOpacity: 0.4,
    cellSize: 8,
    speed: 80,
    density: 0.1,
    interactive: true,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode,
  },
  controls: [
    {
      key: 'backgroundColor',
      label: 'Background Color',
      type: 'color',
      defaultValue: '#ffffff',
      description: 'The background color of the canvas.',
    },
    {
      key: 'cellColor',
      label: 'Cell Color',
      type: 'color',
      defaultValue: '#22c55e',
      description: 'The color of alive cells.',
    },
    {
      key: 'cellOpacity',
      label: 'Cell Opacity',
      type: 'slider',
      min: 0.1,
      max: 1.0,
      step: 0.1,
      defaultValue: 0.4,
      description: 'The opacity of alive cells.',
    },
    {
      key: 'cellSize',
      label: 'Cell Size',
      type: 'slider',
      min: 4,
      max: 20,
      step: 2,
      defaultValue: 8,
      description: 'The size of each cell in pixels.',
    },
    {
      key: 'speed',
      label: 'Speed',
      type: 'slider',
      min: 20,
      max: 300,
      step: 10,
      defaultValue: 80,
      description: 'Milliseconds per simulation step — lower is faster.',
    },
    {
      key: 'density',
      label: 'Initial Density',
      type: 'slider',
      min: 0.01,
      max: 0.5,
      step: 0.01,
      defaultValue: 0.1,
      description: 'Probability of each cell starting alive.',
    },
    {
      key: 'interactive',
      label: 'Mouse Interaction',
      type: 'toggle',
      defaultValue: true,
      description: 'Enable or disable spawning cells with the mouse.',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
