import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code'

export default {
  name: 'Firefly Effect',
  description: 'An interactive particle system where floating orbs ignite and glow intensely when approached by the mouse cursor, creating a bioluminescent effect.',
  author: {
    name: "Ninjafire",
    imageUrl: 'https://pbs.twimg.com/profile_images/2006007847742758912/nWXptCKJ_400x400.jpg',
    redirectUrl: 'https://ninjafire.xyz'
  },
  tags: ['particles', 'interactive', 'glow', 'mouse-effect', 'canvas', 'light'],
  defaultProps: {
    circleCount: 1500,
    speedFactor: 0.8,
    minRadius: 1,
    maxRadius: 10,
    focusRadius: 150,
    glowIntensity: 15,
    backgroundColor: "#000000",
    color1: "#fbf8cc",
    color2: "#fdd835",
    color3: "#fff176",
    color4: "#ffeb3b",
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'circleCount',
      label: 'Particle Count',
      type: 'slider',
      min: 100,
      max: 5000,
      step: 100,
      defaultValue: 1500,
      description: 'The total number of particles floating on the screen.',
    },
    {
      key: 'speedFactor',
      label: 'Speed',
      type: 'slider',
      min: 0.1,
      max: 5,
      step: 0.1,
      defaultValue: 0.8,
      description: 'How fast the particles drift around.',
    },
    {
      key: 'focusRadius',
      label: 'Interaction Radius',
      type: 'slider',
      min: 50,
      max: 500,
      step: 10,
      defaultValue: 150,
      description: 'The distance from the cursor where particles begin to react.',
    },
    {
      key: 'glowIntensity',
      label: 'Glow Intensity',
      type: 'slider',
      min: 0,
      max: 50,
      step: 1,
      defaultValue: 15,
      description: 'The strength of the shadow blur effect when lit.',
    },
    {
      key: 'maxRadius',
      label: 'Max Growth Size',
      type: 'slider',
      min: 2,
      max: 50,
      step: 1,
      defaultValue: 10,
      description: 'The maximum size a particle can reach when fully lit.',
    },
    {
      key: 'intensityPower',
      label: 'Falloff Curve',
      type: 'slider',
      min: 1,
      max: 5,
      step: 0.1,
      defaultValue: 2.5,
      description: 'Controls how sharp the transition is from dark to light.',
    },
    {
      key: 'backgroundColor',
      label: 'Background',
      type: 'color',
      defaultValue: '#000000',
      description: 'The background color of the canvas.',
    },
    {
      key: 'color1',
      label: 'Firefly Color 1',
      type: 'color',
      defaultValue: '#fbf8cc',
      description: 'A variation of the particle color.',
    },
    {
      key: 'color2',
      label: 'Firefly Color 2',
      type: 'color',
      defaultValue: '#fdd835',
      description: 'A variation of the particle color.',
    },
    {
      key: 'color3',
      label: 'Firefly Color 3',
      type: 'color',
      defaultValue: '#fff176',
      description: 'A variation of the particle color.',
    },
    {
      key: 'color4',
      label: 'Firefly Color 4',
      type: 'color',
      defaultValue: '#ffeb3b',
      description: 'A variation of the particle color.',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
