import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code'

export default {
  name: 'Liquid Warp',
  description: 'Flowing liquid distortion effect with layered domain warping',
  author: {
    name: "Ninjafire",
    imageUrl: 'https://pbs.twimg.com/profile_images/2006007847742758912/nWXptCKJ_400x400.jpg',
    redirectUrl: 'https://ninjafire.xyz'
  },
  tags: ['animated', 'shader', 'liquid', 'warp', 'colorful'],
  defaultProps: {
    speed: 0.01,
    warpIntensity: 1.5,
    warpFrequency: 10.0,
    iterations: 10,
    colorSpeed: 0.1,
    colorOffsetR: 0.0,
    colorOffsetG: 2.0,
    colorOffsetB: 4.0,
    brightness: 0.5,
    saturation: 0.5,
    zoom: 1.0,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'speed',
      label: 'Speed',
      type: 'slider',
      min: 0.01,
      max: 0.5,
      step: 0.01,
      defaultValue: 0.01,
      description: 'Overall animation speed',
    },
    {
      key: 'warpIntensity',
      label: 'Warp Intensity',
      type: 'slider',
      min: 0.01,
      max: 3,
      step: 0.01,
      defaultValue: 1.5,
      description: 'Strength of the coordinate distortion per layer',
    },
    {
      key: 'warpFrequency',
      label: 'Warp Frequency',
      type: 'slider',
      min: 1.0,
      max: 30.0,
      step: 0.5,
      defaultValue: 10.0,
      description: 'Oscillation frequency of the warp distortion',
    },
    {
      key: 'iterations',
      label: 'Iterations',
      type: 'slider',
      min: 1,
      max: 30,
      step: 1,
      defaultValue: 10,
      description: 'Number of warp passes — more iterations create denser patterns',
    },
    {
      key: 'zoom',
      label: 'Zoom',
      type: 'slider',
      min: 0.2,
      max: 3.0,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Zoom level of the effect',
    },
    {
      key: 'brightness',
      label: 'Brightness',
      type: 'slider',
      min: 0.0,
      max: 1.0,
      step: 0.05,
      defaultValue: 0.5,
      description: 'Overall brightness of the colors',
    },
    {
      key: 'saturation',
      label: 'Saturation',
      type: 'slider',
      min: 0.0,
      max: 1.0,
      step: 0.05,
      defaultValue: 0.5,
      description: 'Intensity of the color variation',
    },
    {
      key: 'colorSpeed',
      label: 'Color Speed',
      type: 'slider',
      min: 0.01,
      max: 0.5,
      step: 0.01,
      defaultValue: 0.1,
      description: 'How fast the color palette shifts over time',
    },
    {
      key: 'colorOffsetR',
      label: 'Red Phase',
      type: 'slider',
      min: 0.0,
      max: 6.28,
      step: 0.1,
      defaultValue: 0.0,
      description: 'Phase offset for the red channel',
    },
    {
      key: 'colorOffsetG',
      label: 'Green Phase',
      type: 'slider',
      min: 0.0,
      max: 6.28,
      step: 0.1,
      defaultValue: 2.0,
      description: 'Phase offset for the green channel',
    },
    {
      key: 'colorOffsetB',
      label: 'Blue Phase',
      type: 'slider',
      min: 0.0,
      max: 6.28,
      step: 0.1,
      defaultValue: 4.0,
      description: 'Phase offset for the blue channel',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
