import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code';

export default {
  name: 'Solar Flare',
  description: 'A fiery solar flare effect with intense warm colors and dynamic eruptions',
  author: {
    name: "Aryan",
    imageUrl: 'https://pbs.twimg.com/profile_images/1927618320246919168/nvaCh-o8_400x400.jpg',
    redirectUrl: 'https://tarnished.lol'
  },
  tags: ['shader', 'webgl2', 'animated', 'fire', 'sun'],
  defaultProps: {
    speed: 1.0,
    translateX: 1.0,
    translateY: 1.0,
    intensity: 2.0,
    spread: 10.0,
    pulseRate: 0.6,
    colorR: 1.0,
    colorG: 0.4,
    colorB: 0.2,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'speed',
      label: 'Speed',
      type: 'slider',
      min: 0.1,
      max: 3,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Animation speed',
    },
    {
      key: 'translateX',
      label: 'Translate X',
      type: 'slider',
      min: -4,
      max: 4,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Horizontal position of the flare center',
    },
    {
      key: 'translateY',
      label: 'Translate Y',
      type: 'slider',
      min: -3,
      max: 3,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Vertical position of the flare center',
    },
    {
      key: 'intensity',
      label: 'Intensity',
      type: 'slider',
      min: 0.5,
      max: 5.0,
      step: 0.1,
      defaultValue: 2.0,
      description: 'Brightness intensity of the flare',
    },
    {
      key: 'spread',
      label: 'Spread',
      type: 'slider',
      min: 1.0,
      max: 30.0,
      step: 0.5,
      defaultValue: 10.0,
      description: 'How far the flare light spreads outward',
    },
    {
      key: 'pulseRate',
      label: 'Pulse Rate',
      type: 'slider',
      min: 0.1,
      max: 2.0,
      step: 0.1,
      defaultValue: 0.6,
      description: 'Speed of the pulsing animation cycle',
    },
    {
      key: 'colorR',
      label: 'Color Red',
      type: 'slider',
      min: 0,
      max: 1.5,
      step: 0.05,
      defaultValue: 1.0,
      description: 'Red channel of the flare color',
    },
    {
      key: 'colorG',
      label: 'Color Green',
      type: 'slider',
      min: 0,
      max: 1.5,
      step: 0.05,
      defaultValue: 0.4,
      description: 'Green channel of the flare color',
    },
    {
      key: 'colorB',
      label: 'Color Blue',
      type: 'slider',
      min: 0,
      max: 1.5,
      step: 0.05,
      defaultValue: 0.2,
      description: 'Blue channel of the flare color',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
