import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code'

export default {
  name: 'Dot Grid',
  description: 'A dynamic background featuring a grid of dots that displace away from the cursor.',
  author: {
    name: "Aryan",
    imageUrl: 'https://pbs.twimg.com/profile_images/1927618320246919168/nvaCh-o8_400x400.jpg',
    redirectUrl: 'https://tarnished.lol'
  },
  tags: ['animated', 'dotted-grids', 'waves', 'interactive', 'hover-effects', 'geometric'],
  defaultProps: {
    dotSpacing: 30,
    dotBaseSize: 2,
    influenceRadius: 200,
    displacementStrength: 40,
    backgroundColor: '#0a0a0a',
    dotColor: '#646464',
    mouseInteraction: true,
    shape: 'circle',
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'backgroundColor',
      label: 'Background Color',
      type: 'color',
      defaultValue: '#0a0a0a',
      description: 'The overall background color for the dot grid.',
    },
    {
      key: 'dotColor',
      label: 'Dot Color',
      type: 'color',
      defaultValue: '#646464',
      description: 'The color of the dots.',
    },
    {
      key: 'dotSpacing',
      label: 'Dot Spacing',
      type: 'slider',
      min: 20,
      max: 50,
      step: 10,
      defaultValue: 30,
      description: 'The distance between individual dots in the grid.',
    },
    {
      key: 'mouseInteraction',
      label: 'Mouse Interaction',
      type: 'toggle',
      defaultValue: true,
      description: 'Enable or disable the mouse displacement effect.',
    },
    {
      key: 'shape',
      label: 'Shape',
      type: 'select',
      options: ['circle', 'triangle', 'square'],
      defaultValue: 'circle',
      description: 'The shape used for each dot in the grid.',
    },
    {
      key: 'dotBaseSize',
      label: 'Dot Size',
      type: 'slider',
      min: 0.5,
      max: 5,
      step: 0.1,
      defaultValue: 2,
      description: 'The base size of each dot in the grid.',
    },
    {
      key: 'displacementStrength',
      label: 'Displacement Strength',
      type: 'slider',
      min: 0,
      max: 200,
      step: 10,
      defaultValue: 40,
      description: 'How far dots are pushed away from the cursor.',
    },
    {
      key: 'influenceRadius',
      label: 'Influence Radius',
      type: 'slider',
      min: 0,
      max: 400,
      step: 10,
      defaultValue: 200,
      description: 'The radius within which dots respond to the cursor.',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
