import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code';

export default {
  name: 'Vortex Twist',
  description: 'A mesmerizing twisted vortex with swirling patterns and dynamic color shifts',
  author: {
    name: "Ninjafire",
    imageUrl: 'https://pbs.twimg.com/profile_images/2006007847742758912/nWXptCKJ_400x400.jpg',
    redirectUrl: 'https://ninjafire.xyz'
  },
  tags: ['shader', 'webgl2', 'animated', 'vortex', 'abstract'],
  defaultProps: {
    speed: 1.0,
    backgroundColor: '#000000',
    direction: 'clockwise',
    rotation: 0,
    translateX: 0,
    translateY: 0,
    twist: 9,
    zoom: 5,
    intensity: 0.1,
    colorR: 0.0,
    colorG: 0.1,
    colorB: 0.2,
    frequency: 0.61,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'speed',
      label: 'Speed',
      type: 'slider',
      min: 0.1,
      max: 3,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Animation speed',
    },
    {
      key: 'backgroundColor',
      label: 'Background Color',
      type: 'color',
      defaultValue: '#000000',
      description: 'Background color drawn on canvas',
    },
    {
      key: 'direction',
      label: 'Direction',
      type: 'select',
      options: ['clockwise', 'counter-clockwise', 'none'],
      defaultValue: 'clockwise',
      description: 'Direction of vortex rotation',
    },
    {
      key: 'rotation',
      label: 'Rotation',
      type: 'slider',
      min: 0,
      max: 6.28,
      step: 0.01,
      defaultValue: 0,
      description: 'Static rotation angle of the pattern (0 to 2π)',
    },
    {
      key: 'translateX',
      label: 'Translate X',
      type: 'slider',
      min: -3,
      max: 3,
      step: 0.1,
      defaultValue: 0,
      description: 'Horizontal offset of the vortex center',
    },
    {
      key: 'translateY',
      label: 'Translate Y',
      type: 'slider',
      min: -3,
      max: 3,
      step: 0.1,
      defaultValue: 0,
      description: 'Vertical offset of the vortex center',
    },
    {
      key: 'twist',
      label: 'Twist',
      type: 'slider',
      min: 1,
      max: 20,
      step: 0.5,
      defaultValue: 9,
      description: 'Amount of twist in the vortex',
    },
    {
      key: 'zoom',
      label: 'Zoom',
      type: 'slider',
      min: 1,
      max: 15,
      step: 0.5,
      defaultValue: 5,
      description: 'Zoom level of the pattern',
    },
    {
      key: 'intensity',
      label: 'Intensity',
      type: 'slider',
      min: 0.01,
      max: 0.5,
      step: 0.01,
      defaultValue: 0.1,
      description: 'Brightness intensity of the vortex',
    },
    {
      key: 'colorR',
      label: 'Color Red',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.01,
      defaultValue: 0.0,
      description: 'Red channel offset',
    },
    {
      key: 'colorG',
      label: 'Color Green',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.01,
      defaultValue: 0.1,
      description: 'Green channel offset',
    },
    {
      key: 'colorB',
      label: 'Color Blue',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.01,
      defaultValue: 0.2,
      description: 'Blue channel offset',
    },
    {
      key: 'frequency',
      label: 'Frequency',
      type: 'slider',
      min: 0.1,
      max: 2,
      step: 0.01,
      defaultValue: 0.61,
      description: 'Pattern frequency of the swirl',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
