import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code';

export default {
  name: 'Neon Highway',
  description: 'A retro-futuristic neon highway stretching into infinity with pulsing light trails',
  author: {
    name: "Ninjafire",
    imageUrl: 'https://pbs.twimg.com/profile_images/2006007847742758912/nWXptCKJ_400x400.jpg',
    redirectUrl: 'https://ninjafire.xyz'
  },
  tags: ['shader', 'webgl2', 'animated', 'neon', 'retro'],
  defaultProps: {
    speed: 1.0,
    backgroundColor: '#000000',
    translateX: 0,
    translateY: 0,
    zoom: 0.1,
    intensity: 0.4,
    roadWidth: 0.3,
    waveFrequency: 0.6,
    colorR: 0.0,
    colorG: 0.3,
    colorB: 0.6,
    rotation: 0,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'speed',
      label: 'Speed',
      type: 'slider',
      min: 0.1,
      max: 3,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Animation speed',
    },
    {
      key: 'backgroundColor',
      label: 'Background Color',
      type: 'color',
      defaultValue: '#000000',
      description: 'Background color drawn on canvas',
    },
    {
      key: 'translateX',
      label: 'Translate X',
      type: 'slider',
      min: -5,
      max: 5,
      step: 0.1,
      defaultValue: 0,
      description: 'Horizontal offset of the scene',
    },
    {
      key: 'translateY',
      label: 'Translate Y',
      type: 'slider',
      min: -5,
      max: 5,
      step: 0.1,
      defaultValue: 0,
      description: 'Vertical offset of the scene',
    },
    {
      key: 'zoom',
      label: 'Zoom',
      type: 'slider',
      min: 0.02,
      max: 0.5,
      step: 0.01,
      defaultValue: 0.1,
      description: 'Zoom level of the highway pattern',
    },
    {
      key: 'intensity',
      label: 'Intensity',
      type: 'slider',
      min: 0.1,
      max: 1.5,
      step: 0.05,
      defaultValue: 0.4,
      description: 'Brightness intensity of the neon glow',
    },
    {
      key: 'roadWidth',
      label: 'Road Width',
      type: 'slider',
      min: 0.05,
      max: 1.0,
      step: 0.05,
      defaultValue: 0.3,
      description: 'Width of the road perspective',
    },
    {
      key: 'waveFrequency',
      label: 'Wave Frequency',
      type: 'slider',
      min: 0.1,
      max: 2.0,
      step: 0.05,
      defaultValue: 0.6,
      description: 'Frequency of the neon wave pattern',
    },
    {
      key: 'colorR',
      label: 'Color Red',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.01,
      defaultValue: 0.0,
      description: 'Red channel offset',
    },
    {
      key: 'colorG',
      label: 'Color Green',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.01,
      defaultValue: 0.3,
      description: 'Green channel offset',
    },
    {
      key: 'colorB',
      label: 'Color Blue',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.01,
      defaultValue: 0.6,
      description: 'Blue channel offset',
    },
    {
      key: 'rotation',
      label: 'Rotation',
      type: 'slider',
      min: 0,
      max: 6.28,
      step: 0.01,
      defaultValue: 0,
      description: 'Static rotation angle of the pattern (0 to 2π)',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
