import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code'

export default {
  name: 'Snow Fall',
  description: 'Smooth animated Snowfall',
  author: 'NetMods',
  tags: ['animated', 'snowfall', 'snowflakes', 'particles', 'winter', 'falling', 'atmospheric', 'serene'],
  defaultProps: {
    maxSnowflakes: 100,
    snowflakeColor: '#fff',
    backgroundColor: '#000',
    minSize: 7,
    maxSize: 12,
    minSpeed: 0.02,
    maxSpeed: 0.1,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'snowflakeColor',
      label: 'Snowflake Color',
      type: 'color',
      defaultValue: '#fff',
      description: 'The color of the individual snowflakes for a customized wintry glow.',
    },
    {
      key: 'backgroundColor',
      label: 'Background Color',
      type: 'color',
      defaultValue: '#000',
      description: 'The overall background color that sets the night sky or stormy scene for the snowfall.',
    },
    {
      key: 'maxSnowflakes',
      label: 'Max Snowflakes',
      type: 'slider',
      min: 10,
      max: 500,
      step: 20,
      defaultValue: 100,
      description: 'The maximum number of snowflakes visible in the animation at once.',
    },
    {
      key: 'minSize',
      label: 'Min Size',
      type: 'slider',
      min: 0,
      max: 50,
      step: 1,
      defaultValue: 7,
      description: 'The smallest size for snowflake particles to add variety in scale.',
    },
    {
      key: 'maxSize',
      label: 'Max Size',
      type: 'slider',
      min: 0,
      max: 50,
      step: 1,
      defaultValue: 12,
      description: 'The largest size for snowflake particles to create depth in the falling effect.',
    },
    {
      key: 'minSpeed',
      label: 'Min Speed',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.02,
      defaultValue: 0.02,
      description: 'The slowest falling speed for snowflakes to simulate gentle breezes.',
    },
    {
      key: 'maxSpeed',
      label: 'Max Speed',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.1,
      defaultValue: 0.1,
      description: 'The fastest falling speed for snowflakes to add dynamic variation.',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
