import { BackgroundConfig } from '@/lib/types';
import { tsxCode, jsxCode, usageCode } from './code'
export default {
  id: '3',
  name: 'Hexagons',
  description: 'A captivating animated background of glowing hexagon patterns that leave trailing marks as they dynamically evolve.',
  author: 'NetMods',
  tags: ['animated', 'hexagons', 'glowing', 'patterns', 'trails', 'abstract', 'geometric'],
  defaultProps: {
    lineLength: 25,
    maxLineCount: 120,
    baseTime: 10,
    addedTime: 10,
    dieChance: 0.01,
    spawnChance: 1,
    sparkChance: 0.06,
    sparkDistance: 10,
    sparkSize: 2,
    baseLight: 70,
    addedLight: 3,
    shadowToTimePropMultiplier: 2,
    baseLightInputMultiplier: 0.015,
    addedLightInputMultiplier: 0.02,
    repaintAlpha: 0.09,
    hueChange: 0.1,
    backgroundColor: '#000000',
  },
  code: {
    usage: usageCode,
    tsx: tsxCode,
    jsx: jsxCode
  },
  controls: [
    {
      key: 'lineLength',
      label: 'Line Length',
      type: 'slider',
      min: 10,
      max: 100,
      step: 5,
      defaultValue: 25,
      description: 'The length of each line segment used to form the hexagon patterns.',
    },
    {
      key: 'maxLineCount',
      label: 'Max Line Count',
      type: 'slider',
      min: 10,
      max: 200,
      step: 10,
      defaultValue: 120,
      description: 'The maximum number of lines active in the animation at any time.',
    },
    {
      key: 'baseTime',
      label: 'Base Time',
      type: 'slider',
      min: 10,
      max: 100,
      step: 10,
      defaultValue: 10,
      description: 'The base timing factor influencing the speed of hexagon movements.',
    },
    {
      key: 'addedTime',
      label: 'Added Time',
      type: 'slider',
      min: 10,
      max: 100,
      step: 10,
      defaultValue: 10,
      description: 'Additional time variation applied to the animation cycles.',
    },
    {
      key: 'dieChance',
      label: 'Die Chance',
      type: 'slider',
      min: 0,
      max: 0.99,
      step: 0.05,
      defaultValue: 0.01,
      description: 'The probability that a line segment will fade out or "die" in each frame.',
    },
    {
      key: 'spawnChance',
      label: 'Spawn Chance',
      type: 'slider',
      min: 0,
      max: 10,
      step: 1,
      defaultValue: 1,
      description: 'The rate at which new line segments spawn into the pattern.',
    },
    {
      key: 'sparkChance',
      label: 'Spark Chance',
      type: 'slider',
      min: 0,
      max: 2,
      step: 0.01,
      defaultValue: 0.06,
      description: 'The likelihood of generating sparkling effects along the lines.',
    },
    {
      key: 'sparkDistance',
      label: 'Spark Distance',
      type: 'slider',
      min: 0,
      max: 100,
      step: 1,
      defaultValue: 10,
      description: 'The spacing between individual spark points on the lines.',
    },
    {
      key: 'sparkSize',
      label: 'Spark Size',
      type: 'slider',
      min: 0,
      max: 200,
      step: 2,
      defaultValue: 2,
      description: 'The visual size of each spark effect.',
    },
    {
      key: 'baseLight',
      label: 'Base Light',
      type: 'slider',
      min: 0,
      max: 100,
      step: 10,
      defaultValue: 70,
      description: 'The baseline brightness level for the glowing hexagon effects.',
    },
    {
      key: 'repaintAlpha',
      label: 'Repaint Alpha',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.01,
      defaultValue: 0.09,
      description: 'The transparency level applied during each repaint cycle for smooth trails.',
    },
    {
      key: 'backgroundColor',
      label: 'Background Color',
      type: 'color',
      defaultValue: '#000000',
      description: 'The overall background color that contrasts with the glowing hexagons.',
    },
  ],
} as BackgroundConfig;
