import { BackgroundConfig } from '@/lib/types';
import { tsxCode, jsxCode, usageCode } from './code'

export default {
  name: 'Hexagons',
  description: 'Smooth animated Heaxagons patterns that glows and leave a mark',
  author: 'NetMods',
  tags: ['animated', 'gradient', 'waves'],
  defaultProps: {
    lineLength: 25,
    maxLineCount: 120,
    baseTime: 10,
    addedTime: 10,
    dieChance: 0.01,
    spawnChance: 1,
    sparkChance: 0.06,
    sparkDistance: 10,
    sparkSize: 2,
    baseLight: 70,
    addedLight: 3,
    shadowToTimePropMultiplier: 2,
    baseLightInputMultiplier: 0.015,
    addedLightInputMultiplier: 0.02,
    repaintAlpha: 0.09,
    hueChange: 0.1,
    backgroundColor: 'black',

  },
  code: {
    usage: usageCode,
    tsx: tsxCode,
    jsx: jsxCode
  },
  controls: [
    {
      key: 'lineLength',
      label: 'line length',
      type: 'slider',
      min: 10,
      max: 100,
      step: 5,
      defaultvalue: 20,
    },
    {
      key: 'maxLineCount',
      label: 'Line Count',
      type: 'slider',
      min: 10,
      max: 200,
      step: 10,
      defaultvalue: 50,
    },
    {
      key: 'baseTime',
      label: 'Base Time',
      type: 'slider',
      min: 10,
      max: 100,
      step: 10,
      defaultvalue: 10,
    },
    {
      key: 'addedTime',
      label: 'Added Time',
      type: 'slider',
      min: 10,
      max: 100,
      step: 10,
      defaultvalue: 10,
    },
    {
      key: 'dieChance',
      label: 'Die Chance',
      type: 'slider',
      min: 0,
      max: 0.99,
      step: 0.05,
      defaultvalue: 0.05,
    },
    {
      key: 'spawnChance',
      label: 'Spawn Chance',
      type: 'slider',
      min: 0,
      max: 10,
      step: 1,
      defaultvalue: 1,
    },
    {
      key: 'sparkChance',
      label: 'Spark Chance',
      type: 'slider',
      min: 0,
      max: 2,
      step: 0.01,
      defaultvalue: 0.1,
    },
    {
      key: 'sparkDistance',
      label: 'Spark Distance',
      type: 'slider',
      min: 0,
      max: 100,
      step: 1,
      defaultvalue: 10,
    },
    {
      key: 'sparkSize',
      label: 'Spark Size',
      type: 'slider',
      min: 0,
      max: 200,
      step: 2,
      defaultvalue: 2,
    },
    {
      key: 'baseLight',
      label: 'Base Light',
      type: 'slider',
      min: 0,
      max: 100,
      step: 10,
      defaultvalue: 20,
    },
    {
      key: 'repaintAlpha',
      label: 'Repaint Alpha',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.01,
      defaultvalue: 0.09,
    },
    {
      key: 'backgroundColor',
      label: 'background Color',
      type: 'color',
      defaultValue: '#ffffff',
      description: 'backgroundColor',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
