import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code';

export default {
  name: 'Winter Forest',
  description: 'A serene winter scene with parallax trees and gently falling snow',
  author: {
    name: "Aryan",
    imageUrl: 'https://pbs.twimg.com/profile_images/1927618320246919168/nvaCh-o8_400x400.jpg',
    redirectUrl: 'https://tarnished.lol'
  },
  tags: ['canvas', '2d', 'animated', 'winter', 'snow', 'trees'],
  defaultProps: {
    speed: 1.0,
    backgroundColor: '#e8e8e8',
    snowflakeColor: '#ffffff',
    treeColor: '#000000',
    treeCount: 47,
    windStrength: 9,
    snowflakeSize: 2,
    snowSpeed: 99,
    direction: 'right',
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'speed',
      label: 'Speed',
      type: 'slider',
      min: 0.1,
      max: 3,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Animation speed',
    },
    {
      key: 'backgroundColor',
      label: 'Background Color',
      type: 'color',
      defaultValue: '#e8e8e8',
      description: 'Canvas background color',
    },
    {
      key: 'snowflakeColor',
      label: 'Snowflake Color',
      type: 'color',
      defaultValue: '#ffffff',
      description: 'Color of the snowflakes',
    },
    {
      key: 'treeColor',
      label: 'Tree Color',
      type: 'color',
      defaultValue: '#000000',
      description: 'Color of the trees',
    },
    {
      key: 'treeCount',
      label: 'Tree Count',
      type: 'slider',
      min: 10,
      max: 80,
      step: 1,
      defaultValue: 47,
      description: 'Number of tree layers',
    },
    {
      key: 'windStrength',
      label: 'Wind Strength',
      type: 'slider',
      min: 0,
      max: 30,
      step: 1,
      defaultValue: 9,
      description: 'Horizontal sway of snowflakes',
    },
    {
      key: 'snowflakeSize',
      label: 'Snowflake Size',
      type: 'slider',
      min: 1,
      max: 8,
      step: 1,
      defaultValue: 2,
      description: 'Base size of snowflakes',
    },
    {
      key: 'snowSpeed',
      label: 'Snow Speed',
      type: 'slider',
      min: 20,
      max: 200,
      step: 1,
      defaultValue: 99,
      description: 'Falling speed of snowflakes',
    },
    {
      key: 'direction',
      label: 'Direction',
      type: 'select',
      options: ['left', 'right', 'none'],
      defaultValue: 'right',
      description: 'Direction of parallax movement',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
