import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code';

export default {
  name: 'Cellular',
  description: 'Organic cellular patterns that flow and morph like microscopic life forms',
  author: {
    name: "Ninjafire",
    imageUrl: 'https://pbs.twimg.com/profile_images/2006007847742758912/nWXptCKJ_400x400.jpg',
    redirectUrl: 'https://ninjafire.xyz'
  },
  tags: ['shader', 'webgl2', 'animated', 'organic', 'abstract'],
  defaultProps: {
    speed: 1.0,
    scale: 3.0,
    cellSize: 4.0,
    intensity: 0.2,
    distortion: 0.6,
    rotation: 0,
    translateX: 0,
    translateY: 0,
    colorShift: 0.1,
    backgroundColor: '#000000',
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'backgroundColor',
      label: 'Background',
      type: 'color',
      defaultValue: '#000000',
      description: 'Background color',
    },
    {
      key: 'speed',
      label: 'Speed',
      type: 'slider',
      min: 0.1,
      max: 3,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Animation speed',
    },
    {
      key: 'scale',
      label: 'Scale',
      type: 'slider',
      min: 1.0,
      max: 10.0,
      step: 0.5,
      defaultValue: 3.0,
      description: 'Overall zoom level',
    },
    {
      key: 'cellSize',
      label: 'Cell Size',
      type: 'slider',
      min: 1.0,
      max: 10.0,
      step: 0.5,
      defaultValue: 4.0,
      description: 'Size of cellular structures',
    },
    {
      key: 'intensity',
      label: 'Intensity',
      type: 'slider',
      min: 0.05,
      max: 0.5,
      step: 0.01,
      defaultValue: 0.2,
      description: 'Glow intensity',
    },
    {
      key: 'distortion',
      label: 'Distortion',
      type: 'slider',
      min: 0.1,
      max: 2.0,
      step: 0.1,
      defaultValue: 0.6,
      description: 'Pattern distortion amount',
    },
    {
      key: 'colorShift',
      label: 'Color Shift',
      type: 'slider',
      min: 0,
      max: 1.0,
      step: 0.05,
      defaultValue: 0.1,
      description: 'Color variation',
    },
    {
      key: 'rotation',
      label: 'Rotation',
      type: 'slider',
      min: 0,
      max: 6.28,
      step: 0.1,
      defaultValue: 0,
      description: 'Rotation angle (radians)',
    },
    {
      key: 'translateX',
      label: 'Position X',
      type: 'slider',
      min: -5,
      max: 5,
      step: 0.1,
      defaultValue: 0,
      description: 'Horizontal position',
    },
    {
      key: 'translateY',
      label: 'Position Y',
      type: 'slider',
      min: -5,
      max: 5,
      step: 0.1,
      defaultValue: 0,
      description: 'Vertical position',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
