import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code';

export default {
  name: 'Wave Columns',
  description: 'Flowing wave columns that scroll infinitely with smooth sinusoidal curves',
  author: {
    name: "Aryan",
    imageUrl: 'https://pbs.twimg.com/profile_images/1927618320246919168/nvaCh-o8_400x400.jpg',
    redirectUrl: 'https://tarnished.lol'
  },
  tags: ['shader', 'webgl', 'animated', 'waves', 'columns'],
  defaultProps: {
    speed: 1.0,
    theme: 'default',
    rotation: 0,
    translateX: 0,
    translateY: 0,
    scale: 0.3,
    amplitude: 1.0,
    waveCount: 1.0,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'theme',
      label: 'Theme',
      type: 'select',
      options: ['default', 'ocean', 'sunset', 'neon', 'monochrome', 'aurora', 'fire', 'synthwave', 'ice', 'forest'],
      defaultValue: 'default',
      description: 'Color theme for the wave columns',
    },
    {
      key: 'speed',
      label: 'Speed',
      type: 'slider',
      min: 0.1,
      max: 3,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Animation speed',
    },
    {
      key: 'rotation',
      label: 'Rotation',
      type: 'slider',
      min: -180,
      max: 180,
      step: 1,
      defaultValue: 0,
      description: 'Rotation angle in degrees',
    },
    {
      key: 'translateX',
      label: 'Translate X',
      type: 'slider',
      min: -3,
      max: 3,
      step: 0.1,
      defaultValue: 0,
      description: 'Horizontal offset',
    },
    {
      key: 'translateY',
      label: 'Translate Y',
      type: 'slider',
      min: -3,
      max: 3,
      step: 0.1,
      defaultValue: 0,
      description: 'Vertical offset',
    },
    {
      key: 'scale',
      label: 'Scale',
      type: 'slider',
      min: 0.1,
      max: 1.0,
      step: 0.05,
      defaultValue: 0.3,
      description: 'Zoom level of the wave pattern',
    },
    {
      key: 'amplitude',
      label: 'Amplitude',
      type: 'slider',
      min: 0.1,
      max: 3.0,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Height of the wave curves',
    },
    {
      key: 'waveCount',
      label: 'Wave Count',
      type: 'slider',
      min: 0.2,
      max: 4.0,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Density of vertical wave repetitions',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
