import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code';

export default {
  name: 'Three Body',
  description: 'Chaotic three-body gravitational simulation with comet trails',
  author: {
    name: "Aryan",
    imageUrl: 'https://pbs.twimg.com/profile_images/1927618320246919168/nvaCh-o8_400x400.jpg',
    redirectUrl: 'https://tarnished.lol'
  },
  tags: ['canvas', '2d', 'animated', 'physics', 'simulation', 'comets', 'gravity', 'interactive'],
  defaultProps: {
    backgroundColor: '#000000',
    speed: 1,
    cometWidth: 14,
    tailLength: 180,
    coreWidth: 2,
    coreLength: 1,
    coreFade: 0.8,
    mouseAttract: true,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'backgroundColor',
      label: 'Background Color',
      type: 'color',
      defaultValue: '#000000',
      description: 'Canvas background colour',
    },
    {
      key: 'speed',
      label: 'Speed',
      type: 'slider',
      min: 0.1,
      max: 3,
      step: 0.1,
      defaultValue: 1,
      description: 'Physics speed multiplier',
    },
    {
      key: 'cometWidth',
      label: 'Comet Width',
      type: 'slider',
      min: 2,
      max: 30,
      step: 1,
      defaultValue: 14,
      description: 'Maximum comet tail width in pixels',
    },
    {
      key: 'tailLength',
      label: 'Tail Length',
      type: 'slider',
      min: 20,
      max: 400,
      step: 10,
      defaultValue: 180,
      description: 'Number of trail history frames',
    },
    {
      key: 'coreWidth',
      label: 'Core Width',
      type: 'slider',
      min: 1,
      max: 6,
      step: 0.5,
      defaultValue: 2,
      description: 'Center line width in pixels',
    },
    {
      key: 'coreLength',
      label: 'Core Length',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.05,
      defaultValue: 1,
      description: 'Center line length multiplier',
    },
    {
      key: 'coreFade',
      label: 'Core Fade',
      type: 'slider',
      min: 0.1,
      max: 2,
      step: 0.1,
      defaultValue: 0.8,
      description: 'Center line fade exponent — lower = slower fade',
    },
    {
      key: 'mouseAttract',
      label: 'Mouse Attract',
      type: 'toggle',
      defaultValue: true,
      description: 'Mouse cursor acts as a gravitational attractor',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
