import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code'
export default {
  name: 'Bad Television',
  description: 'A CRT/VHS glitch effect with distortion, scanlines, and static noise for images and videos.',
  author: {
    name: "Ninjafire",
    imageUrl: 'https://pbs.twimg.com/profile_images/2006007847742758912/nWXptCKJ_400x400.jpg',
    redirectUrl: 'https://ninjafire.xyz'
  },
  tags: ['glitch', 'crt', 'vhs', 'retro', 'distortion', 'noise', 'television'],
  defaultProps: {
    mediaType: 'image',
    source: '/data/levi.jpeg',
    objectFit: 'cover',
    effectIntensity: 0.5,
    distortion: 0.5,
    noise: 2.5,
    speed: 1,
    scanlines: 0.3,
    rgbShift: 0.3,
    vignette: 0.3,
    flicker: 0.2,
    rollingBar: 0.0,
    brightness: 0,
    contrast: 0,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'mediaType',
      label: 'Media Type',
      type: 'select',
      options: ['image', 'video'],
      defaultValue: 'image',
      description: 'Choose between processing a static image or a looping video.',
    },
    {
      key: 'source',
      label: 'Media Source',
      type: 'media-input',
      defaultValue: '/data/levi.jpeg',
      defaultImage: '/data/levi.jpeg',
      defaultVideo: '/data/levi.mp4',
      description: 'Upload an image or video file to apply the CRT effect.',
      mediaTypeKey: 'mediaType',
    },
    {
      key: 'objectFit',
      label: 'Object Fit',
      type: 'select',
      options: ['contain', 'cover', 'fill'],
      defaultValue: 'cover',
      description: 'Control how the media fits within the canvas.',
    },
    {
      key: 'effectIntensity',
      label: 'Effect Intensity',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.01,
      defaultValue: 0.5,
      description: 'Overall strength of all CRT/VHS effects.',
    },
    {
      key: 'distortion',
      label: 'Distortion',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.01,
      defaultValue: 0.5,
      description: 'Amount of wavy horizontal displacement and glitch jumps.',
    },
    {
      key: 'noise',
      label: 'Noise',
      type: 'slider',
      min: 0,
      max: 8,
      step: 0.01,
      defaultValue: 0.5,
      description: 'Grain and static noise intensity.',
    },
    {
      key: 'speed',
      label: 'Speed',
      type: 'slider',
      min: 0.1,
      max: 3,
      step: 0.1,
      defaultValue: 1,
      description: 'Animation speed multiplier for all time-based effects.',
    },
    {
      key: 'scanlines',
      label: 'Scanlines',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.01,
      defaultValue: 0.3,
      description: 'Intensity of horizontal CRT scanline darkening.',
    },
    {
      key: 'rgbShift',
      label: 'RGB Shift',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.01,
      defaultValue: 0.3,
      description: 'Chromatic aberration / color channel separation.',
    },
    {
      key: 'vignette',
      label: 'Vignette',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.01,
      defaultValue: 0.3,
      description: 'Edge darkening around the screen border.',
    },
    {
      key: 'flicker',
      label: 'Flicker',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.01,
      defaultValue: 0.2,
      description: 'Subtle overall brightness oscillation.',
    },
    {
      key: 'rollingBar',
      label: 'Rolling Bar',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.01,
      defaultValue: 0.0,
      description: 'Classic CRT rolling black bar that scrolls down the screen.',
    },
    {
      key: 'brightness',
      label: 'Brightness',
      type: 'slider',
      min: -100,
      max: 100,
      step: 1,
      defaultValue: 0,
      description: 'Adjust the overall image brightness.',
    },
    {
      key: 'contrast',
      label: 'Contrast',
      type: 'slider',
      min: -100,
      max: 100,
      step: 1,
      defaultValue: 0,
      description: 'Adjust the overall image contrast.',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
