import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code'

export default {
  name: 'Noise Field',
  description: 'An immersive animated background of noise fields where particles elegantly follow fluid flow patterns, evoking organic, wave-like movements.',
  author: 'NetMods',
  tags: ['animated', 'noise', 'flow-field', 'particles', 'organic', 'waves', 'abstract', 'fluid'],
  defaultProps: {
    backgroundColor: '#000000',
    particleNum: 1000,
    step: 1,
    base: 1000,
    zInc: 0.001,
    colorTheme: 'monochrome',
    fadeSpeed: 0,
    maxLines: 500,
    spawnRate: 5,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'backgroundColor',
      label: 'Background Color',
      type: 'color',
      defaultValue: '#000000',
      description: 'The primary color filling the background of the noise field.',
    },
    {
      key: 'particleNum',
      label: 'Particle Number',
      type: 'slider',
      min: 0,
      max: 5000,
      step: 500,
      defaultValue: 1000,
      description: 'The total count of particles generating the noise and flow effects.',
    },
    {
      key: 'step',
      label: 'Step Size',
      type: 'slider',
      min: 0,
      max: 5,
      step: 0.3,
      defaultValue: 1,
      description: 'The incremental step size influencing the smoothness of particle movement.',
    },
    {
      key: 'base',
      label: 'Base Scale',
      type: 'slider',
      min: 0,
      max: 5000,
      step: 500,
      defaultValue: 1000,
      description: 'The foundational scale parameter for the noise field generation.',
    },
    {
      key: 'maxLines',
      label: 'Max Lines',
      type: 'slider',
      min: 100,
      max: 5000,
      step: 100,
      defaultValue: 500,
      description: 'The maximum number of lines or trails rendered in the flow field.',
    },
    {
      key: 'spawnRate',
      label: 'Spawn Rate',
      type: 'slider',
      min: 0,
      max: 20,
      step: 1,
      defaultValue: 5,
      description: 'The frequency at which new particles or elements spawn into the field.',
    },
    {
      key: 'colorTheme',
      label: 'Color Theme',
      type: 'select',
      options: ['rainbow', 'monochrome', 'warm', 'cool', 'gruvbox', 'pastel', 'neon'],
      defaultValue: 'monochrome',
      description: 'The overall color palette applied to the particles and lines in the noise animation.',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
