import { BackgroundConfig } from '@/lib/types';
import { tsxCode, jsxCode, usageCode } from './code'

export default {
  id: '6',
  name: 'Noise Field',
  description: 'Noise fields foloowing the flow field',
  author: 'NetMods',
  tags: ['animated', 'gradient', 'waves'],
  defaultProps: {
    backgroundColor: 'black',
    particleNum: 1000,
    step: 1,
    base: 1000,
    zInc: 0.001,
    colorTheme: 'monochrome',
    fadeSpeed: 0,
    maxLines: 500,
    spawnRate: 5,
  },
  code: {
    usage: usageCode,
    tsx: tsxCode,
    jsx: jsxCode
  },
  controls: [
    {
      key: 'backgroundColor',
      label: 'Color',
      type: 'color',
      defaultValue: '#ffffff',
      description: 'Color for the background',
    },
    {
      key: 'particleNum',
      label: 'Offset',
      type: 'slider',
      min: 0,
      max: 5000,
      step: 500,
      defaultValue: 1000,
    },
    {
      key: 'step',
      label: 'Step',
      type: 'slider',
      min: 0,
      max: 5,
      step: 0.3,
      defaultValue: 1,
    },
    {
      key: 'base',
      label: 'base',
      type: 'slider',
      min: 0,
      max: 5000,
      step: 500,
      defaultValue: 1000,
    },
    {
      key: 'maxLines',
      label: 'Max Lines',
      type: 'slider',
      min: 100,
      max: 5000,
      step: 100,
      defaultValue: 1000,
    },
    {
      key: 'spawnRate',
      label: 'Spawn Rate',
      type: 'slider',
      min: 0,
      max: 20,
      step: 1,
      defaultValue: 5,
    },
    {
      key: 'colorTheme',
      label: 'Color Theme',
      type: 'select',
      options: ['rainbow', 'monochrome', 'warm', 'cool', 'gruvbox', 'pastel', 'neon'],
      defaultValue: 'monochrome',
      description: 'Color Scheme for Noise',
    },
  ],
} as BackgroundConfig;
