import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code';
export default {
  name: 'Aura Ring',
  description: 'A mesmerizing WebGL shader creating a glowing aura effect with customizable shapes, themes, and RGB phase shifting.',
  author: {
    name: "Aryan",
    imageUrl: 'https://pbs.twimg.com/profile_images/1927618320246919168/nvaCh-o8_400x400.jpg',
    redirectUrl: 'https://tarnished.lol'
  },
  tags: ['shader', 'webgl', 'background', 'abstract', 'neon', 'glow', 'aura', 'shapes'],
  defaultProps: {
    speed: 1.0,
    frequency: 10.0,
    intensity: 200.0,
    theme: 'ocean',
    shape: 'circle',
    scale: 0.5,
    offsetX: 0,
    offsetY: 0,
    colorShift: [0, 2, 4],
    backgroundColor: '#000',
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'theme',
      label: 'Color Theme',
      type: 'select',
      options: ['rainbow', 'monochrome', 'ocean', 'sunset', 'forest', 'neon', 'fire', 'aurora', 'candy', 'ice', 'lava', 'synthwave', 'gold', 'matrix'],
      defaultValue: 'ocean',
      description: 'Predefined color palette for the gradient effect.',
    },
    {
      key: 'shape',
      label: 'Shape',
      type: 'select',
      options: ['circle', 'square', 'triangle', 'hexagon', 'star'],
      defaultValue: 'circle',
      description: 'The shape of the glowing aura.',
    },
    {
      key: 'scale',
      label: 'Scale',
      type: 'slider',
      min: 0.1,
      max: 1,
      step: 0.1,
      defaultValue: 0.5,
      description: 'Controls the size of the shape. 1.0 = fits canvas height, <1 = smaller, >1 = larger.',
    },
    {
      key: 'speed',
      label: 'Speed',
      type: 'slider',
      min: 0.1,
      max: 5,
      step: 0.1,
      defaultValue: 1.0,
      description: 'Controls the animation speed of the color cycling.',
    },
    {
      key: 'frequency',
      label: 'Frequency',
      type: 'slider',
      min: 1,
      max: 50,
      step: 1,
      defaultValue: 10.0,
      description: 'Controls the density of the sine waves (the number of "ribbons").',
    },
    {
      key: 'intensity',
      label: 'Intensity (Inverse)',
      type: 'slider',
      min: 10,
      max: 500,
      step: 10,
      defaultValue: 200.0,
      description: 'Controls the glow sharpness. Lower values result in a thicker, brighter glow.',
    },
    {
      key: 'offsetX',
      label: 'Offset X',
      type: 'slider',
      min: -1,
      max: 1,
      step: 0.05,
      defaultValue: 0,
      description: 'Horizontal position of the shape center. -1 = left, 1 = right.',
    },
    {
      key: 'offsetY',
      label: 'Offset Y',
      type: 'slider',
      min: -1,
      max: 1,
      step: 0.05,
      defaultValue: 0,
      description: 'Vertical position of the shape center. -1 = bottom, 1 = top.',
    },
    {
      key: 'backgroundColor',
      label: 'Fallback Color',
      type: 'color',
      defaultValue: '#000',
      description: 'The background color used before the shader loads.',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
