import { BackgroundConfig } from '@/lib/types';
import { jsxCode, tsxCode, tsxCodeHTML, jsxCodeHTML, usageCodeHTML, usageCode } from './code'
export default {
  name: 'Halftone Studio',
  description: 'A WebGL halftone dot filter for images and videos with multiple grid types, dot shapes, and color themes.',
  author: {
    name: "Ninjafire",
    imageUrl: 'https://pbs.twimg.com/profile_images/2006007847742758912/nWXptCKJ_400x400.jpg',
    redirectUrl: 'https://ninjafire.xyz'
  },
  tags: ['halftone', 'dots', 'retro', 'canvas', 'image-processing', 'video', 'print'],
  defaultProps: {
    mediaType: 'image',
    source: '/data/grimmjow.jpg',
    objectFit: 'cover',
    inverted: false,
    colorTheme: 'ink-paper',
    dotStyle: 'classic',
    gridType: 'hex',
    size: 0.03,
    radius: 1.19,
    contrast: 0.5,
    grainMixer: 0.1,
    grainOverlay: 0.21,
    grainSize: 0,
  },
  code: {
    usage: usageCodeHTML,
    rawUsage: usageCode,
    tsx: tsxCodeHTML,
    jsx: jsxCodeHTML,
    rawjsx: jsxCode,
    rawtsx: tsxCode
  },
  controls: [
    {
      key: 'mediaType',
      label: 'Media Type',
      type: 'select',
      options: ['image', 'video'],
      defaultValue: 'image',
      description: 'Choose between processing a static image or a looping video.',
    },
    {
      key: 'source',
      label: 'Media Source',
      type: 'media-input',
      defaultValue: '/data/grimmjow.jpg',
      defaultImage: '/data/grimmjow.jpg',
      defaultVideo: '/data/grimmjow.mp4',
      description: 'Upload an image or video file to apply halftone effects.',
      mediaTypeKey: 'mediaType',
    },
    {
      key: 'objectFit',
      label: 'Object Fit',
      type: 'select',
      options: ['contain', 'cover', 'fill'],
      defaultValue: 'cover',
      description: 'Control how the media fits within the canvas.',
    },
    {
      key: 'inverted',
      label: 'Inverted',
      type: 'toggle',
      defaultValue: false,
      description: 'Invert the luminance so bright areas become dark and vice versa.',
    },
    {
      key: 'colorTheme',
      label: 'Color Theme',
      type: 'select',
      options: ['colorful', 'monochrome', 'ink-paper', 'amber-glow', 'game-boy', 'nes', 'terminal', 'blueprint', 'neon-punk'],
      defaultValue: 'ink-paper',
      description: 'Choose a color theme for the halftone output.',
    },
    {
      key: 'dotStyle',
      label: 'Dot Style',
      type: 'select',
      options: ['classic', 'gooney'],
      defaultValue: 'classic',
      description: 'Choose the shape and falloff of the halftone dots.',
    },
    {
      key: 'gridType',
      label: 'Grid Type',
      type: 'select',
      options: ['hex', 'square'],
      defaultValue: 'hex',
      description: 'Choose between hexagonal (traditional halftone) or square grid layout.',
    },
    {
      key: 'size',
      label: 'Dot Size',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.01,
      defaultValue: 0.03,
      description: 'Control the density of halftone dots (smaller value = more dots).',
    },
    {
      key: 'radius',
      label: 'Dot Radius',
      type: 'slider',
      min: 0,
      max: 2,
      step: 0.01,
      defaultValue: 1.19,
      description: 'Scale the maximum radius of each dot relative to the cell size.',
    },
    {
      key: 'contrast',
      label: 'Contrast',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.01,
      defaultValue: 0.5,
      description: 'Apply a sigmoid contrast curve to the luminance.',
    },
    {
      key: 'grainMixer',
      label: 'Grain Mixer',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.01,
      defaultValue: 0.1,
      description: 'Add noise to distort dot edges for a rougher print look.',
    },
    {
      key: 'grainOverlay',
      label: 'Grain Overlay',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.01,
      defaultValue: 0.21,
      description: 'Overlay black and white grain on the final image.',
    },
    {
      key: 'grainSize',
      label: 'Grain Size',
      type: 'slider',
      min: 0,
      max: 1,
      step: 0.01,
      defaultValue: 0.0,
      description: 'Control the scale of the grain noise pattern.',
    },
  ],
} as Omit<BackgroundConfig, 'id'>;
